export type WebsiteItem = {
  name: string;
  url: string;
  category: string;
  description: string;
  freeNote: string;
  suitableFor: string;
};

export const websites: WebsiteItem[] = [
  { name: "Notion", url: "https://www.notion.so", category: "Productivity", description: "Catatan, wiki, dan manajemen tugas all-in-one.", freeNote: "Free untuk personal", suitableFor: "Pelajar, tim kecil" },
  { name: "Trello", url: "https://trello.com", category: "Productivity", description: "Kanban board untuk proyek dan to-do.", freeNote: "Free dengan batas fitur advanced", suitableFor: "Tim, freelancer" },
  { name: "ClickUp", url: "https://clickup.com", category: "Productivity", description: "Manajemen tugas dan project tracking.", freeNote: "Free dengan batas automations", suitableFor: "Tim startup" },
  { name: "Asana", url: "https://asana.com", category: "Productivity", description: "Project management untuk task kolaboratif.", freeNote: "Free untuk tim kecil", suitableFor: "Tim kerja" },
  { name: "Airtable", url: "https://www.airtable.com", category: "Productivity", description: "Spreadsheet plus database visual.", freeNote: "Free dengan limit records", suitableFor: "Operasional, admin" },
  { name: "Todoist", url: "https://todoist.com", category: "Productivity", description: "To-do list ringan dan cepat.", freeNote: "Free fitur dasar", suitableFor: "Individu" },
  { name: "Google Keep", url: "https://keep.google.com", category: "Productivity", description: "Catatan cepat dan checklist.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Google Docs", url: "https://docs.google.com", category: "Productivity", description: "Dokumen online untuk menulis dan kolaborasi.", freeNote: "Gratis, tanpa langganan", suitableFor: "Pelajar, tim kecil" },
  { name: "Google Forms", url: "https://forms.google.com", category: "Productivity", description: "Buat formulir, survey, dan kuis online.", freeNote: "Gratis, tanpa langganan", suitableFor: "Guru, admin, UMKM" },
  { name: "diagrams.net", url: "https://www.diagrams.net", category: "Productivity", description: "Buat flowchart, diagram, dan wireframe online.", freeNote: "Gratis, tanpa langganan", suitableFor: "Tim produk, pelajar" },
  { name: "Clockify", url: "https://clockify.me", category: "Productivity", description: "Pelacakan waktu kerja.", freeNote: "Free plan kuat", suitableFor: "Freelancer, agency" },
  { name: "Toggl Track", url: "https://toggl.com/track", category: "Productivity", description: "Time tracker sederhana.", freeNote: "Free dasar", suitableFor: "Freelancer" },
  { name: "Pomofocus", url: "https://pomofocus.io", category: "Productivity", description: "Timer Pomodoro berbasis web.", freeNote: "Gratis", suitableFor: "Belajar, fokus" },

  { name: "Khan Academy", url: "https://www.khanacademy.org", category: "Education", description: "Belajar matematika, sains, dan lainnya.", freeNote: "Gratis", suitableFor: "Pelajar" },
  { name: "Coursera", url: "https://www.coursera.org", category: "Education", description: "Kursus kampus global mode audit.", freeNote: "Banyak materi gratis", suitableFor: "Mahasiswa, profesional" },
  { name: "edX", url: "https://www.edx.org", category: "Education", description: "Kelas online dari universitas top.", freeNote: "Audit gratis", suitableFor: "Upskilling" },
  { name: "MIT OpenCourseWare", url: "https://ocw.mit.edu", category: "Education", description: "Materi kuliah MIT gratis.", freeNote: "Gratis penuh", suitableFor: "Self-learner" },
  { name: "freeCodeCamp", url: "https://www.freecodecamp.org", category: "Education", description: "Belajar coding interaktif plus sertifikasi.", freeNote: "Gratis penuh", suitableFor: "Calon developer" },
  { name: "The Odin Project", url: "https://www.theodinproject.com", category: "Education", description: "Kurikulum web dev terstruktur.", freeNote: "Gratis penuh", suitableFor: "Pemula coding" },
  { name: "W3Schools", url: "https://www.w3schools.com", category: "Education", description: "Referensi cepat HTML, CSS, dan JS.", freeNote: "Gratis", suitableFor: "Pemula web" },
  { name: "Codecademy", url: "https://www.codecademy.com", category: "Education", description: "Belajar coding interaktif.", freeNote: "Sebagian materi gratis", suitableFor: "Pemula coding" },
  { name: "OpenStax", url: "https://openstax.org", category: "Education", description: "Buku ajar gratis untuk pelajar dan mahasiswa.", freeNote: "Gratis, tanpa langganan", suitableFor: "Pelajar, mahasiswa" },
  { name: "Duolingo", url: "https://www.duolingo.com", category: "Education", description: "Belajar bahasa dengan gamifikasi.", freeNote: "Free dengan iklan", suitableFor: "Bahasa asing" },
  { name: "Alison", url: "https://alison.com", category: "Education", description: "Kursus keterampilan kerja.", freeNote: "Banyak kursus gratis", suitableFor: "Pencari skill kerja" },
  { name: "Generate CV Free", url: "https://cepetcv.vercel.app/", category: "Career", description: "Buat CV profesional secara gratis.", freeNote: "Gratis", suitableFor: "Pencari kerja" },

  { name: "GitHub", url: "https://github.com", category: "Developer", description: "Hosting kode dan kolaborasi.", freeNote: "Free repo publik dan privat", suitableFor: "Developer" },
  { name: "GitLab", url: "https://gitlab.com", category: "Developer", description: "Repo, CI/CD, dan issue tracking.", freeNote: "Free plan tersedia", suitableFor: "Dev team" },
  { name: "Stack Overflow", url: "https://stackoverflow.com", category: "Developer", description: "QnA teknis pemrograman.", freeNote: "Gratis", suitableFor: "Programmer" },
  { name: "MDN Web Docs", url: "https://developer.mozilla.org", category: "Developer", description: "Dokumentasi web lengkap.", freeNote: "Gratis", suitableFor: "Web developer" },
  { name: "DevDocs", url: "https://devdocs.io", category: "Developer", description: "Dokumentasi API cepat dalam satu tempat.", freeNote: "Gratis", suitableFor: "Developer" },
  { name: "CodePen", url: "https://codepen.io", category: "Developer", description: "Playground frontend online.", freeNote: "Free plan ada", suitableFor: "Frontend" },
  { name: "JSFiddle", url: "https://jsfiddle.net", category: "Developer", description: "Uji cepat snippet HTML, CSS, JS.", freeNote: "Gratis", suitableFor: "Frontend" },
  { name: "JSONPlaceholder", url: "https://jsonplaceholder.typicode.com", category: "Developer", description: "Fake API gratis untuk testing dan demo.", freeNote: "Gratis, tanpa langganan", suitableFor: "Backend dev, QA" },
  { name: "Can I use", url: "https://caniuse.com", category: "Developer", description: "Cek kompatibilitas fitur web browser.", freeNote: "Gratis, tanpa langganan", suitableFor: "Frontend dev" },
  { name: "Selenium IDE", url: "https://www.selenium.dev/selenium-ide/", category: "Developer", description: "Tool rekam dan automasi testing web.", freeNote: "Gratis, tanpa langganan", suitableFor: "QA, automation" },
  { name: "Replit", url: "https://replit.com", category: "Developer", description: "Menulis dan jalankan kode di browser.", freeNote: "Free dengan batas resource", suitableFor: "Pelajar coding" },
  { name: "Vercel", url: "https://vercel.com", category: "Developer", description: "Deploy frontend dan Next.js instan.", freeNote: "Hobby plan gratis", suitableFor: "Frontend dev" },
  { name: "Netlify", url: "https://www.netlify.com", category: "Developer", description: "Deploy static dan Jamstack.", freeNote: "Free plan tersedia", suitableFor: "Web dev" },

  { name: "Figma", url: "https://www.figma.com", category: "Design", description: "UI/UX design kolaboratif.", freeNote: "Free starter", suitableFor: "UI/UX designer" },
  { name: "Canva", url: "https://www.canva.com", category: "Design", description: "Desain konten cepat.", freeNote: "Free banyak template", suitableFor: "Konten kreator" },
  { name: "Adobe Express", url: "https://www.adobe.com/express", category: "Design", description: "Desain sosial media sederhana.", freeNote: "Free plan tersedia", suitableFor: "Marketing" },
  { name: "Penpot", url: "https://penpot.app", category: "Design", description: "Tool UI/UX open-source.", freeNote: "Gratis", suitableFor: "Tim desain" },
  { name: "Unsplash", url: "https://unsplash.com", category: "Design", description: "Foto stok berkualitas tinggi.", freeNote: "Gratis", suitableFor: "Kreator" },
  { name: "Pexels", url: "https://www.pexels.com", category: "Design", description: "Foto dan video stok gratis.", freeNote: "Gratis", suitableFor: "Kreator" },
  { name: "Pixabay", url: "https://pixabay.com", category: "Design", description: "Gambar, video, ilustrasi gratis.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Figma Community", url: "https://www.figma.com/community", category: "Design", description: "Template, UI kit, dan resource desain gratis.", freeNote: "Gratis, tanpa langganan", suitableFor: "UI/UX designer" },
  { name: "Coolors", url: "https://coolors.co", category: "Design", description: "Generator palet warna cepat.", freeNote: "Gratis, tanpa langganan", suitableFor: "Designer" },
  { name: "Flaticon", url: "https://www.flaticon.com", category: "Design", description: "Ikon siap pakai.", freeNote: "Free dengan atribusi", suitableFor: "Designer, dev" },
  { name: "unDraw", url: "https://undraw.co/illustrations", category: "Design", description: "Ilustrasi SVG gratis.", freeNote: "Gratis", suitableFor: "UI designer" },

  { name: "ChatGPT", url: "https://chat.openai.com", category: "AI", description: "Asisten ide, menulis, dan coding.", freeNote: "Free tier tersedia", suitableFor: "Umum" },
  { name: "Gemini", url: "https://gemini.google.com", category: "AI", description: "Asisten AI dari Google.", freeNote: "Free tier tersedia", suitableFor: "Umum" },
  { name: "Claude", url: "https://claude.ai", category: "AI", description: "AI assistant untuk analisis teks.", freeNote: "Free tier tersedia", suitableFor: "Profesional" },
  { name: "Perplexity", url: "https://www.perplexity.ai", category: "AI", description: "Mesin jawaban dengan referensi web.", freeNote: "Free plan tersedia", suitableFor: "Riset cepat" },
  { name: "Hugging Face", url: "https://huggingface.co", category: "AI", description: "Model AI, dataset, dan demo.", freeNote: "Banyak fitur gratis", suitableFor: "Developer AI" },
  { name: "Poe", url: "https://poe.com", category: "AI", description: "Akses beberapa model AI.", freeNote: "Free terbatas", suitableFor: "Umum" },
  { name: "Clipdrop", url: "https://clipdrop.co", category: "AI", description: "Tool AI gambar dan edit cepat.", freeNote: "Free terbatas", suitableFor: "Kreator" },
  { name: "ElevenLabs", url: "https://elevenlabs.io", category: "AI", description: "Text-to-speech natural.", freeNote: "Free kuota bulanan", suitableFor: "Konten audio" },
  { name: "Leonardo AI", url: "https://leonardo.ai", category: "AI", description: "Generate gambar AI.", freeNote: "Free token harian", suitableFor: "Kreator visual" },

  { name: "LinkedIn", url: "https://www.linkedin.com", category: "Career", description: "Profil profesional dan networking.", freeNote: "Gratis", suitableFor: "Job seeker" },
  { name: "Indeed", url: "https://www.indeed.com", category: "Career", description: "Mesin pencari lowongan kerja.", freeNote: "Gratis", suitableFor: "Pencari kerja" },
  { name: "Glassdoor", url: "https://www.glassdoor.com", category: "Career", description: "Review perusahaan dan gaji.", freeNote: "Gratis", suitableFor: "Pencari kerja" },
  { name: "Jobstreet", url: "https://www.jobstreet.com", category: "Career", description: "Portal lowongan regional Asia.", freeNote: "Gratis", suitableFor: "Job seeker" },
  { name: "Kalibrr", url: "https://www.kalibrr.com", category: "Career", description: "Platform kerja dan rekrutmen.", freeNote: "Gratis", suitableFor: "Fresh graduate" },
  { name: "Glints", url: "https://glints.com", category: "Career", description: "Lowongan dan pengembangan karier.", freeNote: "Gratis", suitableFor: "Mahasiswa, profesional" },
  { name: "Upwork", url: "https://www.upwork.com", category: "Career", description: "Marketplace jasa freelance global.", freeNote: "Gratis daftar", suitableFor: "Freelancer" },
  { name: "Fiverr", url: "https://www.fiverr.com", category: "Career", description: "Jual jasa digital per paket.", freeNote: "Gratis daftar", suitableFor: "Freelancer pemula" },

  { name: "Google Drive", url: "https://drive.google.com", category: "Utilities", description: "Penyimpanan cloud dan berbagi file.", freeNote: "15GB gratis", suitableFor: "Umum" },
  { name: "Dropbox", url: "https://www.dropbox.com", category: "Utilities", description: "Cloud storage sinkronisasi file.", freeNote: "Free kapasitas terbatas", suitableFor: "Umum" },
  { name: "WeTransfer", url: "https://wetransfer.com", category: "Utilities", description: "Kirim file besar cepat.", freeNote: "Free limit ukuran", suitableFor: "Umum" },
  { name: "PDF24 Tools", url: "https://tools.pdf24.org", category: "Utilities", description: "Edit, gabung, kompres PDF.", freeNote: "Gratis", suitableFor: "Kantor, pelajar" },
  { name: "iLovePDF", url: "https://www.ilovepdf.com", category: "Utilities", description: "Konversi dan edit PDF.", freeNote: "Free dengan limit harian", suitableFor: "Umum" },
  { name: "Smallpdf", url: "https://smallpdf.com", category: "Utilities", description: "Tool PDF online praktis.", freeNote: "Free task terbatas", suitableFor: "Profesional" },
  { name: "TinyWow", url: "https://tinywow.com", category: "Utilities", description: "Tool PDF, video, dan image.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Remove.bg", url: "https://www.remove.bg", category: "Utilities", description: "Hapus background gambar otomatis.", freeNote: "Gratis untuk penggunaan dasar", suitableFor: "Desainer, seller" },
  { name: "TinyPNG", url: "https://tinypng.com", category: "Utilities", description: "Kompres PNG dan JPG dengan cepat.", freeNote: "Gratis untuk penggunaan dasar", suitableFor: "Web owner" },
  { name: "Speedtest", url: "https://www.speedtest.net", category: "Utilities", description: "Cek kecepatan internet.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Temp Mail", url: "https://temp-mail.org", category: "Utilities", description: "Email sementara.", freeNote: "Gratis", suitableFor: "Verifikasi cepat" },
  { name: "Bitly", url: "https://bitly.com", category: "Utilities", description: "Short link plus tracking dasar.", freeNote: "Free plan tersedia", suitableFor: "Marketing" },

  { name: "VirusTotal", url: "https://www.virustotal.com", category: "Security", description: "Scan file dan URL dari banyak engine.", freeNote: "Gratis", suitableFor: "Keamanan personal" },
  { name: "Have I Been Pwned", url: "https://haveibeenpwned.com", category: "Security", description: "Cek apakah email bocor data.", freeNote: "Gratis", suitableFor: "Semua pengguna" },
  { name: "PrivacyGuides", url: "https://www.privacyguides.org", category: "Security", description: "Panduan tool privasi terpercaya.", freeNote: "Gratis", suitableFor: "Privasi digital" },
  { name: "Proton Mail", url: "https://proton.me/mail", category: "Security", description: "Email terenkripsi.", freeNote: "Free plan tersedia", suitableFor: "Privasi tinggi" },
  { name: "Bitwarden", url: "https://bitwarden.com", category: "Security", description: "Password manager open-source.", freeNote: "Free personal kuat", suitableFor: "Semua pengguna" },
  { name: "DuckDuckGo", url: "https://duckduckgo.com", category: "Security", description: "Mesin pencari fokus privasi.", freeNote: "Gratis", suitableFor: "Pengguna umum" },
  { name: "2FA Directory", url: "https://2fa.directory", category: "Security", description: "Cek layanan yang dukung 2FA.", freeNote: "Gratis", suitableFor: "Pengguna sadar keamanan" },
  { name: "Mozilla Monitor", url: "https://monitor.mozilla.org", category: "Security", description: "Cek kebocoran data akun.", freeNote: "Gratis", suitableFor: "Semua pengguna" },

  { name: "Wave", url: "https://www.waveapps.com", category: "Business", description: "Akuntansi gratis untuk UMKM.", freeNote: "Gratis inti", suitableFor: "UMKM, freelancer" },
  { name: "Zoho Invoice", url: "https://www.zoho.com/invoice", category: "Business", description: "Buat invoice dan pelacakan pembayaran.", freeNote: "Free plan tersedia", suitableFor: "Freelancer" },
  { name: "Invoice Ninja", url: "https://www.invoiceninja.com", category: "Business", description: "Invoice, quote, dan pembayaran.", freeNote: "Free plan tersedia", suitableFor: "Agency kecil" },
  { name: "Google Sheets", url: "https://sheets.google.com", category: "Business", description: "Budgeting, laporan, dan tracking kas.", freeNote: "Gratis", suitableFor: "Semua pengguna" },
  { name: "Wise", url: "https://wise.com", category: "Business", description: "Transfer uang lintas negara murah.", freeNote: "Akun gratis", suitableFor: "Freelancer global" },
  { name: "XE", url: "https://www.xe.com", category: "Business", description: "Konversi kurs real-time.", freeNote: "Gratis", suitableFor: "Bisnis internasional" },
  { name: "Similarweb", url: "https://www.similarweb.com", category: "Business", description: "Estimasi traffic website.", freeNote: "Free data terbatas", suitableFor: "Marketer" },
  { name: "Statista", url: "https://www.statista.com", category: "Business", description: "Data statistik pasar dan industri.", freeNote: "Sebagian konten gratis", suitableFor: "Riset bisnis" },

  { name: "MedlinePlus", url: "https://medlineplus.gov", category: "Health", description: "Informasi kesehatan tepercaya.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Mayo Clinic", url: "https://www.mayoclinic.org", category: "Health", description: "Referensi medis dan gejala.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Sleep Foundation", url: "https://www.sleepfoundation.org", category: "Health", description: "Edukasi tidur dan recovery.", freeNote: "Gratis", suitableFor: "Produktivitas personal" },
  { name: "MyFitnessPal", url: "https://www.myfitnesspal.com", category: "Health", description: "Tracking kalori dan nutrisi.", freeNote: "Free plan tersedia", suitableFor: "Diet dan fitness" },
  { name: "Nike Training Club", url: "https://www.nike.com/ntc-app", category: "Health", description: "Program workout gratis.", freeNote: "Gratis", suitableFor: "Fitness pemula" },
  { name: "Insight Timer", url: "https://insighttimer.com", category: "Health", description: "Meditasi dan relaksasi.", freeNote: "Free banyak konten", suitableFor: "Mental wellness" },

  { name: "FutureLearn", url: "https://www.futurelearn.com", category: "Education", description: "Kursus online berbagai topik.", freeNote: "Banyak kelas gratis periode tertentu", suitableFor: "Pembelajar umum" },
  { name: "Memrise", url: "https://www.memrise.com", category: "Education", description: "Latihan kosakata dan percakapan.", freeNote: "Free terbatas", suitableFor: "Belajar bahasa" },
  { name: "Postman", url: "https://www.postman.com", category: "Developer", description: "Testing dan dokumentasi API.", freeNote: "Free plan tersedia", suitableFor: "Backend dev" },
  { name: "Hoppscotch", url: "https://hoppscotch.io", category: "Developer", description: "API client ringan berbasis web.", freeNote: "Gratis", suitableFor: "API testing" },
  { name: "regex101", url: "https://regex101.com", category: "Developer", description: "Tester regex dengan penjelasan.", freeNote: "Gratis", suitableFor: "Developer" },
  { name: "Calendly", url: "https://calendly.com", category: "Productivity", description: "Jadwal meeting otomatis.", freeNote: "Free 1 jenis event", suitableFor: "Konsultan, sales" },
  { name: "Miro", url: "https://miro.com", category: "Productivity", description: "Whiteboard online kolaboratif.", freeNote: "Free terbatas board", suitableFor: "Brainstorming tim" },
  { name: "Downdetector", url: "https://downdetector.com", category: "Utilities", description: "Pantau gangguan layanan online.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "10 Minute Mail", url: "https://10minutemail.com", category: "Utilities", description: "Email sementara singkat.", freeNote: "Gratis", suitableFor: "Verifikasi cepat" },

  { name: "Nike Run Club", url: "https://www.nike.com/nrc-app", category: "Health", description: "Pelacakan lari dan program latihan.", freeNote: "Gratis", suitableFor: "Pelari pemula" },
  { name: "Tana", url: "https://tana.inc", category: "Productivity", description: "Knowledge graph untuk catatan kerja.", freeNote: "Free plan tersedia", suitableFor: "Power user" },
  { name: "Linear", url: "https://linear.app", category: "Productivity", description: "Issue tracker cepat untuk tim produk.", freeNote: "Free untuk personal", suitableFor: "Startup tech" },
  { name: "Excalidraw", url: "https://excalidraw.com", category: "Productivity", description: "Sketsa diagram cepat ala whiteboard.", freeNote: "Gratis", suitableFor: "Tim produk" },
  { name: "Photopea", url: "https://www.photopea.com", category: "Design", description: "Editor gambar berbasis web mirip Photoshop.", freeNote: "Gratis dengan iklan", suitableFor: "Designer" },
  { name: "Dribbble", url: "https://dribbble.com", category: "Design", description: "Inspirasi desain dan showcase karya.", freeNote: "Gratis", suitableFor: "Desainer" },
  { name: "Behance", url: "https://www.behance.net", category: "Design", description: "Portofolio kreatif global.", freeNote: "Gratis", suitableFor: "Kreator" },
  { name: "Loom", url: "https://www.loom.com", category: "Productivity", description: "Rekam layar dan jelaskan ide cepat.", freeNote: "Free plan tersedia", suitableFor: "Remote worker" },

  { name: "Google Trends", url: "https://trends.google.com", category: "Business", description: "Lihat tren pencarian topik.", freeNote: "Gratis", suitableFor: "Marketer, peneliti" },
  { name: "AnswerThePublic", url: "https://answerthepublic.com", category: "Business", description: "Ide keyword dan pertanyaan audiens.", freeNote: "Free terbatas", suitableFor: "Content strategist" },
  { name: "Ubersuggest", url: "https://neilpatel.com/ubersuggest", category: "Business", description: "Riset keyword dan SEO dasar.", freeNote: "Free terbatas", suitableFor: "Marketer" },
  { name: "Namechk", url: "https://namechk.com", category: "Business", description: "Cek ketersediaan nama brand dan username.", freeNote: "Gratis", suitableFor: "Founder" },
  { name: "Carrd", url: "https://carrd.co", category: "Business", description: "Buat landing page sederhana cepat.", freeNote: "Free basic", suitableFor: "Personal brand" },
  { name: "Buffer", url: "https://buffer.com", category: "Business", description: "Penjadwalan konten sosial media.", freeNote: "Free channel terbatas", suitableFor: "Creator" },
  { name: "Metricool", url: "https://metricool.com", category: "Business", description: "Analitik dan jadwal sosial media.", freeNote: "Free plan tersedia", suitableFor: "Social media manager" },
  { name: "RescueTime", url: "https://www.rescuetime.com", category: "Productivity", description: "Analisis kebiasaan penggunaan waktu digital.", freeNote: "Lite free", suitableFor: "Produktivitas personal" },
  { name: "Habitica", url: "https://habitica.com", category: "Productivity", description: "To-do list bergaya game RPG.", freeNote: "Gratis", suitableFor: "Gamified productivity" },
  { name: "Forest", url: "https://www.forestapp.cc", category: "Productivity", description: "Teknik fokus dengan timer visual.", freeNote: "Web info gratis", suitableFor: "Fokus belajar" },

  { name: "OpenLibrary", url: "https://openlibrary.org", category: "Education", description: "Katalog buku digital terbuka.", freeNote: "Gratis", suitableFor: "Pembaca" },
  { name: "Project Gutenberg", url: "https://www.gutenberg.org", category: "Education", description: "Ribuan ebook klasik gratis.", freeNote: "Gratis", suitableFor: "Pelajar, pembaca" },
  { name: "Scholar Google", url: "https://scholar.google.com", category: "Education", description: "Pencarian jurnal dan paper ilmiah.", freeNote: "Gratis", suitableFor: "Peneliti" },
  { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov", category: "Health", description: "Basis data literatur biomedis.", freeNote: "Gratis", suitableFor: "Mahasiswa kesehatan" },
  { name: "Cronometer", url: "https://cronometer.com", category: "Health", description: "Tracking nutrisi detail.", freeNote: "Free plan tersedia", suitableFor: "Fitness enthusiast" },
  { name: "Zero", url: "https://www.zerolongevity.com", category: "Health", description: "Pelacak fasting dan pola makan.", freeNote: "Free plan tersedia", suitableFor: "Intermittent fasting" },
  { name: "Canva Docs", url: "https://www.canva.com/docs", category: "Productivity", description: "Dokumen kolaboratif visual.", freeNote: "Free plan tersedia", suitableFor: "Tim kreatif" },
  { name: "Whimsical", url: "https://whimsical.com", category: "Productivity", description: "Flowchart, wireframe, dan mindmap.", freeNote: "Free item terbatas", suitableFor: "Product team" },
  { name: "Raycast Extensions", url: "https://www.raycast.com/store", category: "Developer", description: "Kumpulan extension produktivitas developer.", freeNote: "Gratis", suitableFor: "Developer" },
  { name: "JSON Formatter", url: "https://jsonformatter.org", category: "Developer", description: "Format dan validasi JSON online.", freeNote: "Gratis", suitableFor: "Developer" },
];

export const websiteCategories = [
  "All",
  ...new Set(websites.map((item) => item.category)),
];


