export type WebsiteItem = {
  name: string;
  url: string;
  category: string;
  description: string;
  freeNote: string;
  suitableFor: string;
};

export const websites: WebsiteItem[] = [
  { name: "Notion", url: "https://www.notion.so", category: "Productivity", description: "Catatan, wiki, dan manajemen tugas all-in-one.", freeNote: "Free untuk personal", suitableFor: "Pelajar, tim kecil" },
  { name: "Trello", url: "https://trello.com", category: "Productivity", description: "Kanban board untuk proyek dan to-do.", freeNote: "Free dengan batas fitur advanced", suitableFor: "Tim, freelancer" },
  { name: "ClickUp", url: "https://clickup.com", category: "Productivity", description: "Manajemen tugas dan project tracking.", freeNote: "Free dengan batas automations", suitableFor: "Tim startup" },
  { name: "Asana", url: "https://asana.com", category: "Productivity", description: "Project management untuk task kolaboratif.", freeNote: "Free untuk tim kecil", suitableFor: "Tim kerja" },
  { name: "Airtable", url: "https://www.airtable.com", category: "Productivity", description: "Spreadsheet plus database visual.", freeNote: "Free dengan limit records", suitableFor: "Operasional, admin" },
  { name: "Todoist", url: "https://todoist.com", category: "Productivity", description: "To-do list ringan dan cepat.", freeNote: "Free fitur dasar", suitableFor: "Individu" },
  { name: "Google Keep", url: "https://keep.google.com", category: "Productivity", description: "Catatan cepat dan checklist.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Google Docs", url: "https://docs.google.com", category: "Productivity", description: "Dokumen online untuk menulis dan kolaborasi.", freeNote: "Gratis, tanpa langganan", suitableFor: "Pelajar, tim kecil" },
  { name: "Google Forms", url: "https://forms.google.com", category: "Productivity", description: "Buat formulir, survey, dan kuis online.", freeNote: "Gratis, tanpa langganan", suitableFor: "Guru, admin, UMKM" },
  { name: "diagrams.net", url: "https://www.diagrams.net", category: "Productivity", description: "Buat flowchart, diagram, dan wireframe online.", freeNote: "Gratis, tanpa langganan", suitableFor: "Tim produk, pelajar" },
  { name: "Clockify", url: "https://clockify.me", category: "Productivity", description: "Pelacakan waktu kerja.", freeNote: "Free plan kuat", suitableFor: "Freelancer, agency" },
  { name: "Toggl Track", url: "https://toggl.com/track", category: "Productivity", description: "Time tracker sederhana.", freeNote: "Free dasar", suitableFor: "Freelancer" },
  { name: "Pomofocus", url: "https://pomofocus.io", category: "Productivity", description: "Timer Pomodoro berbasis web.", freeNote: "Gratis", suitableFor: "Belajar, fokus" },

  { name: "Khan Academy", url: "https://www.khanacademy.org", category: "Education", description: "Belajar matematika, sains, dan lainnya.", freeNote: "Gratis", suitableFor: "Pelajar" },
  { name: "Coursera", url: "https://www.coursera.org", category: "Education", description: "Kursus kampus global mode audit.", freeNote: "Banyak materi gratis", suitableFor: "Mahasiswa, profesional" },
  { name: "edX", url: "https://www.edx.org", category: "Education", description: "Kelas online dari universitas top.", freeNote: "Audit gratis", suitableFor: "Upskilling" },
  { name: "MIT OpenCourseWare", url: "https://ocw.mit.edu", category: "Education", description: "Materi kuliah MIT gratis.", freeNote: "Gratis penuh", suitableFor: "Self-learner" },
  { name: "freeCodeCamp", url: "https://www.freecodecamp.org", category: "Education", description: "Belajar coding interaktif plus sertifikasi.", freeNote: "Gratis penuh", suitableFor: "Calon developer" },
  { name: "The Odin Project", url: "https://www.theodinproject.com", category: "Education", description: "Kurikulum web dev terstruktur.", freeNote: "Gratis penuh", suitableFor: "Pemula coding" },
  { name: "W3Schools", url: "https://www.w3schools.com", category: "Education", description: "Referensi cepat HTML, CSS, dan JS.", freeNote: "Gratis", suitableFor: "Pemula web" },
  { name: "Codecademy", url: "https://www.codecademy.com", category: "Education", description: "Belajar coding interaktif.", freeNote: "Sebagian materi gratis", suitableFor: "Pemula coding" },
  { name: "OpenStax", url: "https://openstax.org", category: "Education", description: "Buku ajar gratis untuk pelajar dan mahasiswa.", freeNote: "Gratis, tanpa langganan", suitableFor: "Pelajar, mahasiswa" },
  { name: "Duolingo", url: "https://www.duolingo.com", category: "Education", description: "Belajar bahasa dengan gamifikasi.", freeNote: "Free dengan iklan", suitableFor: "Bahasa asing" },
  { name: "Alison", url: "https://alison.com", category: "Education", description: "Kursus keterampilan kerja.", freeNote: "Banyak kursus gratis", suitableFor: "Pencari skill kerja" },
  { name: "Generate CV Free", url: "https://cepetcv.vercel.app/", category: "Career", description: "Buat CV profesional secara gratis.", freeNote: "Gratis", suitableFor: "Pencari kerja" },

  { name: "GitHub", url: "https://github.com", category: "Developer", description: "Hosting kode dan kolaborasi.", freeNote: "Free repo publik dan privat", suitableFor: "Developer" },
  { name: "GitLab", url: "https://gitlab.com", category: "Developer", description: "Repo, CI/CD, dan issue tracking.", freeNote: "Free plan tersedia", suitableFor: "Dev team" },
  { name: "Stack Overflow", url: "https://stackoverflow.com", category: "Developer", description: "QnA teknis pemrograman.", freeNote: "Gratis", suitableFor: "Programmer" },
  { name: "MDN Web Docs", url: "https://developer.mozilla.org", category: "Developer", description: "Dokumentasi web lengkap.", freeNote: "Gratis", suitableFor: "Web developer" },
  { name: "DevDocs", url: "https://devdocs.io", category: "Developer", description: "Dokumentasi API cepat dalam satu tempat.", freeNote: "Gratis", suitableFor: "Developer" },
  { name: "CodePen", url: "https://codepen.io", category: "Developer", description: "Playground frontend online.", freeNote: "Free plan ada", suitableFor: "Frontend" },
  { name: "JSFiddle", url: "https://jsfiddle.net", category: "Developer", description: "Uji cepat snippet HTML, CSS, JS.", freeNote: "Gratis", suitableFor: "Frontend" },
  { name: "JSONPlaceholder", url: "https://jsonplaceholder.typicode.com", category: "Developer", description: "Fake API gratis untuk testing dan demo.", freeNote: "Gratis, tanpa langganan", suitableFor: "Backend dev, QA" },
  { name: "Can I use", url: "https://caniuse.com", category: "Developer", description: "Cek kompatibilitas fitur web browser.", freeNote: "Gratis, tanpa langganan", suitableFor: "Frontend dev" },
  { name: "Selenium IDE", url: "https://www.selenium.dev/selenium-ide/", category: "Developer", description: "Tool rekam dan automasi testing web.", freeNote: "Gratis, tanpa langganan", suitableFor: "QA, automation" },
  { name: "Replit", url: "https://replit.com", category: "Developer", description: "Menulis dan jalankan kode di browser.", freeNote: "Free dengan batas resource", suitableFor: "Pelajar coding" },
  { name: "Vercel", url: "https://vercel.com", category: "Developer", description: "Deploy frontend dan Next.js instan.", freeNote: "Hobby plan gratis", suitableFor: "Frontend dev" },
  { name: "Netlify", url: "https://www.netlify.com", category: "Developer", description: "Deploy static dan Jamstack.", freeNote: "Free plan tersedia", suitableFor: "Web dev" },

  { name: "Figma", url: "https://www.figma.com", category: "Design", description: "UI/UX design kolaboratif.", freeNote: "Free starter", suitableFor: "UI/UX designer" },
  { name: "Canva", url: "https://www.canva.com", category: "Design", description: "Desain konten cepat.", freeNote: "Free banyak template", suitableFor: "Konten kreator" },
  { name: "Adobe Express", url: "https://www.adobe.com/express", category: "Design", description: "Desain sosial media sederhana.", freeNote: "Free plan tersedia", suitableFor: "Marketing" },
  { name: "Penpot", url: "https://penpot.app", category: "Design", description: "Tool UI/UX open-source.", freeNote: "Gratis", suitableFor: "Tim desain" },
  { name: "Unsplash", url: "https://unsplash.com", category: "Design", description: "Foto stok berkualitas tinggi.", freeNote: "Gratis", suitableFor: "Kreator" },
  { name: "Pexels", url: "https://www.pexels.com", category: "Design", description: "Foto dan video stok gratis.", freeNote: "Gratis", suitableFor: "Kreator" },
  { name: "Pixabay", url: "https://pixabay.com", category: "Design", description: "Gambar, video, ilustrasi gratis.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Figma Community", url: "https://www.figma.com/community", category: "Design", description: "Template, UI kit, dan resource desain gratis.", freeNote: "Gratis, tanpa langganan", suitableFor: "UI/UX designer" },
  { name: "Coolors", url: "https://coolors.co", category: "Design", description: "Generator palet warna cepat.", freeNote: "Gratis, tanpa langganan", suitableFor: "Designer" },
  { name: "Flaticon", url: "https://www.flaticon.com", category: "Design", description: "Ikon siap pakai.", freeNote: "Free dengan atribusi", suitableFor: "Designer, dev" },
  { name: "unDraw", url: "https://undraw.co/illustrations", category: "Design", description: "Ilustrasi SVG gratis.", freeNote: "Gratis", suitableFor: "UI designer" },

  { name: "ChatGPT", url: "https://chat.openai.com", category: "AI", description: "Asisten ide, menulis, dan coding.", freeNote: "Free tier tersedia", suitableFor: "Umum" },
  { name: "Gemini", url: "https://gemini.google.com", category: "AI", description: "Asisten AI dari Google.", freeNote: "Free tier tersedia", suitableFor: "Umum" },
  { name: "Claude", url: "https://claude.ai", category: "AI", description: "AI assistant untuk analisis teks.", freeNote: "Free tier tersedia", suitableFor: "Profesional" },
  { name: "Perplexity", url: "https://www.perplexity.ai", category: "AI", description: "Mesin jawaban dengan referensi web.", freeNote: "Free plan tersedia", suitableFor: "Riset cepat" },
  { name: "Hugging Face", url: "https://huggingface.co", category: "AI", description: "Model AI, dataset, dan demo.", freeNote: "Banyak fitur gratis", suitableFor: "Developer AI" },
  { name: "Poe", url: "https://poe.com", category: "AI", description: "Akses beberapa model AI.", freeNote: "Free terbatas", suitableFor: "Umum" },
  { name: "Clipdrop", url: "https://clipdrop.co", category: "AI", description: "Tool AI gambar dan edit cepat.", freeNote: "Free terbatas", suitableFor: "Kreator" },
  { name: "ElevenLabs", url: "https://elevenlabs.io", category: "AI", description: "Text-to-speech natural.", freeNote: "Free kuota bulanan", suitableFor: "Konten audio" },
  { name: "Leonardo AI", url: "https://leonardo.ai", category: "AI", description: "Generate gambar AI.", freeNote: "Free token harian", suitableFor: "Kreator visual" },

  { name: "LinkedIn", url: "https://www.linkedin.com", category: "Career", description: "Profil profesional dan networking.", freeNote: "Gratis", suitableFor: "Job seeker" },
  { name: "Indeed", url: "https://www.indeed.com", category: "Career", description: "Mesin pencari lowongan kerja.", freeNote: "Gratis", suitableFor: "Pencari kerja" },
  { name: "Glassdoor", url: "https://www.glassdoor.com", category: "Career", description: "Review perusahaan dan gaji.", freeNote: "Gratis", suitableFor: "Pencari kerja" },
  { name: "Jobstreet", url: "https://www.jobstreet.com", category: "Career", description: "Portal lowongan regional Asia.", freeNote: "Gratis", suitableFor: "Job seeker" },
  { name: "Kalibrr", url: "https://www.kalibrr.com", category: "Career", description: "Platform kerja dan rekrutmen.", freeNote: "Gratis", suitableFor: "Fresh graduate" },
  { name: "Glints", url: "https://glints.com", category: "Career", description: "Lowongan dan pengembangan karier.", freeNote: "Gratis", suitableFor: "Mahasiswa, profesional" },
  { name: "Upwork", url: "https://www.upwork.com", category: "Career", description: "Marketplace jasa freelance global.", freeNote: "Gratis daftar", suitableFor: "Freelancer" },
  { name: "Fiverr", url: "https://www.fiverr.com", category: "Career", description: "Jual jasa digital per paket.", freeNote: "Gratis daftar", suitableFor: "Freelancer pemula" },

  { name: "Google Drive", url: "https://drive.google.com", category: "Utilities", description: "Penyimpanan cloud dan berbagi file.", freeNote: "15GB gratis", suitableFor: "Umum" },
  { name: "Dropbox", url: "https://www.dropbox.com", category: "Utilities", description: "Cloud storage sinkronisasi file.", freeNote: "Free kapasitas terbatas", suitableFor: "Umum" },
  { name: "WeTransfer", url: "https://wetransfer.com", category: "Utilities", description: "Kirim file besar cepat.", freeNote: "Free limit ukuran", suitableFor: "Umum" },
  { name: "PDF24 Tools", url: "https://tools.pdf24.org", category: "Utilities", description: "Edit, gabung, kompres PDF.", freeNote: "Gratis", suitableFor: "Kantor, pelajar" },
  { name: "iLovePDF", url: "https://www.ilovepdf.com", category: "Utilities", description: "Konversi dan edit PDF.", freeNote: "Free dengan limit harian", suitableFor: "Umum" },
  { name: "Smallpdf", url: "https://smallpdf.com", category: "Utilities", description: "Tool PDF online praktis.", freeNote: "Free task terbatas", suitableFor: "Profesional" },
  { name: "TinyWow", url: "https://tinywow.com", category: "Utilities", description: "Tool PDF, video, dan image.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Remove.bg", url: "https://www.remove.bg", category: "Utilities", description: "Hapus background gambar otomatis.", freeNote: "Gratis untuk penggunaan dasar", suitableFor: "Desainer, seller" },
  { name: "TinyPNG", url: "https://tinypng.com", category: "Utilities", description: "Kompres PNG dan JPG dengan cepat.", freeNote: "Gratis untuk penggunaan dasar", suitableFor: "Web owner" },
  { name: "Speedtest", url: "https://www.speedtest.net", category: "Utilities", description: "Cek kecepatan internet.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Temp Mail", url: "https://temp-mail.org", category: "Utilities", description: "Email sementara.", freeNote: "Gratis", suitableFor: "Verifikasi cepat" },
  { name: "Bitly", url: "https://bitly.com", category: "Utilities", description: "Short link plus tracking dasar.", freeNote: "Free plan tersedia", suitableFor: "Marketing" },

  { name: "VirusTotal", url: "https://www.virustotal.com", category: "Security", description: "Scan file dan URL dari banyak engine.", freeNote: "Gratis", suitableFor: "Keamanan personal" },
  { name: "Have I Been Pwned", url: "https://haveibeenpwned.com", category: "Security", description: "Cek apakah email bocor data.", freeNote: "Gratis", suitableFor: "Semua pengguna" },
  { name: "PrivacyGuides", url: "https://www.privacyguides.org", category: "Security", description: "Panduan tool privasi terpercaya.", freeNote: "Gratis", suitableFor: "Privasi digital" },
  { name: "Proton Mail", url: "https://proton.me/mail", category: "Security", description: "Email terenkripsi.", freeNote: "Free plan tersedia", suitableFor: "Privasi tinggi" },
  { name: "Bitwarden", url: "https://bitwarden.com", category: "Security", description: "Password manager open-source.", freeNote: "Free personal kuat", suitableFor: "Semua pengguna" },
  { name: "DuckDuckGo", url: "https://duckduckgo.com", category: "Security", description: "Mesin pencari fokus privasi.", freeNote: "Gratis", suitableFor: "Pengguna umum" },
  { name: "2FA Directory", url: "https://2fa.directory", category: "Security", description: "Cek layanan yang dukung 2FA.", freeNote: "Gratis", suitableFor: "Pengguna sadar keamanan" },
  { name: "Mozilla Monitor", url: "https://monitor.mozilla.org", category: "Security", description: "Cek kebocoran data akun.", freeNote: "Gratis", suitableFor: "Semua pengguna" },

  { name: "Wave", url: "https://www.waveapps.com", category: "Business", description: "Akuntansi gratis untuk UMKM.", freeNote: "Gratis inti", suitableFor: "UMKM, freelancer" },
  { name: "Zoho Invoice", url: "https://www.zoho.com/invoice", category: "Business", description: "Buat invoice dan pelacakan pembayaran.", freeNote: "Free plan tersedia", suitableFor: "Freelancer" },
  { name: "Invoice Ninja", url: "https://www.invoiceninja.com", category: "Business", description: "Invoice, quote, dan pembayaran.", freeNote: "Free plan tersedia", suitableFor: "Agency kecil" },
  { name: "Google Sheets", url: "https://sheets.google.com", category: "Business", description: "Budgeting, laporan, dan tracking kas.", freeNote: "Gratis", suitableFor: "Semua pengguna" },
  { name: "Wise", url: "https://wise.com", category: "Business", description: "Transfer uang lintas negara murah.", freeNote: "Akun gratis", suitableFor: "Freelancer global" },
  { name: "XE", url: "https://www.xe.com", category: "Business", description: "Konversi kurs real-time.", freeNote: "Gratis", suitableFor: "Bisnis internasional" },
  { name: "Similarweb", url: "https://www.similarweb.com", category: "Business", description: "Estimasi traffic website.", freeNote: "Free data terbatas", suitableFor: "Marketer" },
  { name: "Statista", url: "https://www.statista.com", category: "Business", description: "Data statistik pasar dan industri.", freeNote: "Sebagian konten gratis", suitableFor: "Riset bisnis" },

  { name: "MedlinePlus", url: "https://medlineplus.gov", category: "Health", description: "Informasi kesehatan tepercaya.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Mayo Clinic", url: "https://www.mayoclinic.org", category: "Health", description: "Referensi medis dan gejala.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Sleep Foundation", url: "https://www.sleepfoundation.org", category: "Health", description: "Edukasi tidur dan recovery.", freeNote: "Gratis", suitableFor: "Produktivitas personal" },
  { name: "MyFitnessPal", url: "https://www.myfitnesspal.com", category: "Health", description: "Tracking kalori dan nutrisi.", freeNote: "Free plan tersedia", suitableFor: "Diet dan fitness" },
  { name: "Nike Training Club", url: "https://www.nike.com/ntc-app", category: "Health", description: "Program workout gratis.", freeNote: "Gratis", suitableFor: "Fitness pemula" },
  { name: "Insight Timer", url: "https://insighttimer.com", category: "Health", description: "Meditasi dan relaksasi.", freeNote: "Free banyak konten", suitableFor: "Mental wellness" },

  { name: "FutureLearn", url: "https://www.futurelearn.com", category: "Education", description: "Kursus online berbagai topik.", freeNote: "Banyak kelas gratis periode tertentu", suitableFor: "Pembelajar umum" },
  { name: "Memrise", url: "https://www.memrise.com", category: "Education", description: "Latihan kosakata dan percakapan.", freeNote: "Free terbatas", suitableFor: "Belajar bahasa" },
  { name: "Postman", url: "https://www.postman.com", category: "Developer", description: "Testing dan dokumentasi API.", freeNote: "Free plan tersedia", suitableFor: "Backend dev" },
  { name: "Hoppscotch", url: "https://hoppscotch.io", category: "Developer", description: "API client ringan berbasis web.", freeNote: "Gratis", suitableFor: "API testing" },
  { name: "regex101", url: "https://regex101.com", category: "Developer", description: "Tester regex dengan penjelasan.", freeNote: "Gratis", suitableFor: "Developer" },
  { name: "Calendly", url: "https://calendly.com", category: "Productivity", description: "Jadwal meeting otomatis.", freeNote: "Free 1 jenis event", suitableFor: "Konsultan, sales" },
  { name: "Miro", url: "https://miro.com", category: "Productivity", description: "Whiteboard online kolaboratif.", freeNote: "Free terbatas board", suitableFor: "Brainstorming tim" },
  { name: "Downdetector", url: "https://downdetector.com", category: "Utilities", description: "Pantau gangguan layanan online.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "10 Minute Mail", url: "https://10minutemail.com", category: "Utilities", description: "Email sementara singkat.", freeNote: "Gratis", suitableFor: "Verifikasi cepat" },

  { name: "Nike Run Club", url: "https://www.nike.com/nrc-app", category: "Health", description: "Pelacakan lari dan program latihan.", freeNote: "Gratis", suitableFor: "Pelari pemula" },
  { name: "Tana", url: "https://tana.inc", category: "Productivity", description: "Knowledge graph untuk catatan kerja.", freeNote: "Free plan tersedia", suitableFor: "Power user" },
  { name: "Linear", url: "https://linear.app", category: "Productivity", description: "Issue tracker cepat untuk tim produk.", freeNote: "Free untuk personal", suitableFor: "Startup tech" },
  { name: "Excalidraw", url: "https://excalidraw.com", category: "Productivity", description: "Sketsa diagram cepat ala whiteboard.", freeNote: "Gratis", suitableFor: "Tim produk" },
  { name: "Photopea", url: "https://www.photopea.com", category: "Design", description: "Editor gambar berbasis web mirip Photoshop.", freeNote: "Gratis dengan iklan", suitableFor: "Designer" },
  { name: "Dribbble", url: "https://dribbble.com", category: "Design", description: "Inspirasi desain dan showcase karya.", freeNote: "Gratis", suitableFor: "Desainer" },
  { name: "Behance", url: "https://www.behance.net", category: "Design", description: "Portofolio kreatif global.", freeNote: "Gratis", suitableFor: "Kreator" },
  { name: "Loom", url: "https://www.loom.com", category: "Productivity", description: "Rekam layar dan jelaskan ide cepat.", freeNote: "Free plan tersedia", suitableFor: "Remote worker" },

  { name: "Google Trends", url: "https://trends.google.com", category: "Business", description: "Lihat tren pencarian topik.", freeNote: "Gratis", suitableFor: "Marketer, peneliti" },
  { name: "AnswerThePublic", url: "https://answerthepublic.com", category: "Business", description: "Ide keyword dan pertanyaan audiens.", freeNote: "Free terbatas", suitableFor: "Content strategist" },
  { name: "Ubersuggest", url: "https://neilpatel.com/ubersuggest", category: "Business", description: "Riset keyword dan SEO dasar.", freeNote: "Free terbatas", suitableFor: "Marketer" },
  { name: "Namechk", url: "https://namechk.com", category: "Business", description: "Cek ketersediaan nama brand dan username.", freeNote: "Gratis", suitableFor: "Founder" },
  { name: "Carrd", url: "https://carrd.co", category: "Business", description: "Buat landing page sederhana cepat.", freeNote: "Free basic", suitableFor: "Personal brand" },
  { name: "Buffer", url: "https://buffer.com", category: "Business", description: "Penjadwalan konten sosial media.", freeNote: "Free channel terbatas", suitableFor: "Creator" },
  { name: "Metricool", url: "https://metricool.com", category: "Business", description: "Analitik dan jadwal sosial media.", freeNote: "Free plan tersedia", suitableFor: "Social media manager" },
  { name: "RescueTime", url: "https://www.rescuetime.com", category: "Productivity", description: "Analisis kebiasaan penggunaan waktu digital.", freeNote: "Lite free", suitableFor: "Produktivitas personal" },
  { name: "Habitica", url: "https://habitica.com", category: "Productivity", description: "To-do list bergaya game RPG.", freeNote: "Gratis", suitableFor: "Gamified productivity" },
  { name: "Forest", url: "https://www.forestapp.cc", category: "Productivity", description: "Teknik fokus dengan timer visual.", freeNote: "Web info gratis", suitableFor: "Fokus belajar" },

  { name: "OpenLibrary", url: "https://openlibrary.org", category: "Education", description: "Katalog buku digital terbuka.", freeNote: "Gratis", suitableFor: "Pembaca" },
  { name: "Project Gutenberg", url: "https://www.gutenberg.org", category: "Education", description: "Ribuan ebook klasik gratis.", freeNote: "Gratis", suitableFor: "Pelajar, pembaca" },
  { name: "Scholar Google", url: "https://scholar.google.com", category: "Education", description: "Pencarian jurnal dan paper ilmiah.", freeNote: "Gratis", suitableFor: "Peneliti" },
  { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov", category: "Health", description: "Basis data literatur biomedis.", freeNote: "Gratis", suitableFor: "Mahasiswa kesehatan" },
  { name: "Cronometer", url: "https://cronometer.com", category: "Health", description: "Tracking nutrisi detail.", freeNote: "Free plan tersedia", suitableFor: "Fitness enthusiast" },
  { name: "Zero", url: "https://www.zerolongevity.com", category: "Health", description: "Pelacak fasting dan pola makan.", freeNote: "Free plan tersedia", suitableFor: "Intermittent fasting" },
  { name: "Canva Docs", url: "https://www.canva.com/docs", category: "Productivity", description: "Dokumen kolaboratif visual.", freeNote: "Free plan tersedia", suitableFor: "Tim kreatif" },
  { name: "Whimsical", url: "https://whimsical.com", category: "Productivity", description: "Flowchart, wireframe, dan mindmap.", freeNote: "Free item terbatas", suitableFor: "Product team" },
  { name: "Raycast Extensions", url: "https://www.raycast.com/store", category: "Developer", description: "Kumpulan extension produktivitas developer.", freeNote: "Gratis", suitableFor: "Developer" },
  { name: "JSON Formatter", url: "https://jsonformatter.org", category: "Developer", description: "Format dan validasi JSON online.", freeNote: "Gratis", suitableFor: "Developer" },
  { name: "Obsidian", url: "https://obsidian.md", category: "Productivity", description: "Catatan terhubung berbasis markdown.", freeNote: "Gratis untuk penggunaan personal", suitableFor: "Writer, knowledge worker" },
  { name: "Any.do", url: "https://www.any.do", category: "Productivity", description: "To-do list, planner, dan reminder harian.", freeNote: "Free plan tersedia", suitableFor: "Individu" },
  { name: "Jira", url: "https://www.atlassian.com/software/jira", category: "Productivity", description: "Issue tracking dan manajemen sprint tim.", freeNote: "Free untuk tim kecil", suitableFor: "Tim produk, engineering" },
  { name: "Coda", url: "https://coda.io", category: "Productivity", description: "Dokumen interaktif untuk workflow tim.", freeNote: "Free plan tersedia", suitableFor: "Tim operasional" },
  { name: "Readwise Reader", url: "https://readwise.io/read", category: "Productivity", description: "Simpan, baca, dan highlight artikel dalam satu tempat.", freeNote: "Trial tersedia", suitableFor: "Researcher, pembaca aktif" },

  { name: "LeetCode", url: "https://leetcode.com", category: "Education", description: "Latihan coding interview dan algoritma.", freeNote: "Banyak soal gratis", suitableFor: "Calon software engineer" },
  { name: "Roadmap.sh", url: "https://roadmap.sh", category: "Education", description: "Peta belajar karier teknologi yang terstruktur.", freeNote: "Gratis", suitableFor: "Pemula hingga menengah" },
  { name: "Harvard CS50", url: "https://cs50.harvard.edu", category: "Education", description: "Materi ilmu komputer dasar dari Harvard.", freeNote: "Gratis", suitableFor: "Pemula coding" },

  { name: "Supabase", url: "https://supabase.com", category: "Developer", description: "Backend open-source dengan database Postgres.", freeNote: "Free tier tersedia", suitableFor: "Full-stack developer" },
  { name: "Railway", url: "https://railway.app", category: "Developer", description: "Deploy aplikasi dan database dengan cepat.", freeNote: "Trial credit tersedia", suitableFor: "Indie hacker" },
  { name: "Render", url: "https://render.com", category: "Developer", description: "Hosting web app, API, dan worker.", freeNote: "Free plan tersedia", suitableFor: "Developer" },
  { name: "Snyk", url: "https://snyk.io", category: "Developer", description: "Cek kerentanan dependency dan container.", freeNote: "Free untuk individu", suitableFor: "Developer, security" },
  { name: "PostHog", url: "https://posthog.com", category: "Developer", description: "Product analytics, feature flags, dan session replay.", freeNote: "Free tier tersedia", suitableFor: "Product engineer" },

  { name: "LottieFiles", url: "https://lottiefiles.com", category: "Design", description: "Koleksi dan preview animasi Lottie.", freeNote: "Free plan tersedia", suitableFor: "UI motion designer" },
  { name: "Noun Project", url: "https://thenounproject.com", category: "Design", description: "Koleksi ikon dan ilustrasi siap pakai.", freeNote: "Free dengan atribusi", suitableFor: "Designer, marketer" },
  { name: "Fontshare", url: "https://www.fontshare.com", category: "Design", description: "Font modern gratis untuk komersial.", freeNote: "Gratis", suitableFor: "Designer, branding" },

  { name: "CloudConvert", url: "https://cloudconvert.com", category: "Utilities", description: "Konversi berbagai format file secara online.", freeNote: "Free kuota harian", suitableFor: "Umum" },
  { name: "Jotform", url: "https://www.jotform.com", category: "Utilities", description: "Buat form online dengan template siap pakai.", freeNote: "Free plan tersedia", suitableFor: "UMKM, admin" },
  { name: "TransferNow", url: "https://www.transfernow.net", category: "Utilities", description: "Kirim file besar tanpa ribet.", freeNote: "Free plan tersedia", suitableFor: "Umum" },

  { name: "Google Analytics", url: "https://analytics.google.com", category: "Business", description: "Analitik traffic website dan perilaku pengguna.", freeNote: "Gratis", suitableFor: "Owner website, marketer" },
  { name: "HubSpot CRM", url: "https://www.hubspot.com/products/crm", category: "Business", description: "CRM gratis untuk kelola lead dan pipeline.", freeNote: "Free tools tersedia", suitableFor: "Sales, startup" },
  { name: "MailerLite", url: "https://www.mailerlite.com", category: "Business", description: "Email marketing dan automation sederhana.", freeNote: "Free plan tersedia", suitableFor: "Creator, UMKM" },
  { name: "Kit", url: "https://kit.com", category: "Business", description: "Email marketing untuk kreator dan newsletter.", freeNote: "Free plan tersedia", suitableFor: "Creator" },
  { name: "Brevo", url: "https://www.brevo.com", category: "Business", description: "Email marketing, automation, dan CRM ringan.", freeNote: "Free plan tersedia", suitableFor: "UMKM" },
  { name: "Typeform", url: "https://www.typeform.com", category: "Business", description: "Form dan survei interaktif untuk lead generation.", freeNote: "Free plan terbatas", suitableFor: "Marketer" },
  { name: "Tally", url: "https://tally.so", category: "Business", description: "Form builder simpel dengan tampilan modern.", freeNote: "Free plan kuat", suitableFor: "Startup, creator" },

  { name: "Krita", url: "https://krita.org", category: "Design", description: "Aplikasi open-source untuk digital painting.", freeNote: "Gratis", suitableFor: "Ilustrator" },
  { name: "Framer", url: "https://www.framer.com", category: "Design", description: "Desain dan publish website interaktif.", freeNote: "Free plan tersedia", suitableFor: "Designer, startup" },
  { name: "Spline", url: "https://spline.design", category: "Design", description: "Desain 3D interaktif langsung di browser.", freeNote: "Free plan tersedia", suitableFor: "3D designer" },
  { name: "Mobbin", url: "https://mobbin.com", category: "Design", description: "Referensi UI pattern dari aplikasi populer.", freeNote: "Free akses terbatas", suitableFor: "UI designer" },

  { name: "Exercism", url: "https://exercism.org", category: "Education", description: "Latihan coding dengan mentoring komunitas.", freeNote: "Gratis", suitableFor: "Pemula hingga menengah" },
  { name: "Brilliant", url: "https://brilliant.org", category: "Education", description: "Belajar matematika dan logika secara interaktif.", freeNote: "Pelajaran dasar gratis", suitableFor: "Pelajar" },
  { name: "Saylor Academy", url: "https://www.saylor.org", category: "Education", description: "Kursus online gratis dengan materi terstruktur.", freeNote: "Gratis", suitableFor: "Mahasiswa, upskilling" },
  { name: "OpenLearn", url: "https://www.open.edu/openlearn", category: "Education", description: "Kursus terbuka dari The Open University.", freeNote: "Gratis", suitableFor: "Pembelajar umum" },

  { name: "Deno", url: "https://deno.com", category: "Developer", description: "Runtime modern untuk JavaScript dan TypeScript.", freeNote: "Gratis", suitableFor: "Backend developer" },
  { name: "Bun", url: "https://bun.sh", category: "Developer", description: "Runtime dan toolkit JavaScript berperforma tinggi.", freeNote: "Gratis", suitableFor: "Full-stack developer" },
  { name: "CodeSandbox", url: "https://codesandbox.io", category: "Developer", description: "IDE cloud untuk prototype dan kolaborasi cepat.", freeNote: "Free plan tersedia", suitableFor: "Frontend dev" },
  { name: "Glitch", url: "https://glitch.com", category: "Developer", description: "Bangun dan hosting web app langsung dari browser.", freeNote: "Free plan tersedia", suitableFor: "Pemula web" },

  { name: "Tuta", url: "https://tuta.com", category: "Security", description: "Email terenkripsi dengan fokus privasi.", freeNote: "Free plan tersedia", suitableFor: "Privasi digital" },
  { name: "SimpleLogin", url: "https://simplelogin.io", category: "Security", description: "Alias email untuk lindungi identitas utama.", freeNote: "Free plan tersedia", suitableFor: "Pengguna umum" },
  { name: "Aegis Authenticator", url: "https://getaegis.app", category: "Security", description: "Aplikasi 2FA open-source untuk Android.", freeNote: "Gratis", suitableFor: "Pengguna Android" },

  { name: "Otter.ai", url: "https://otter.ai", category: "Productivity", description: "Transkripsi meeting dan catatan otomatis.", freeNote: "Free plan tersedia", suitableFor: "Meeting, kuliah" },
  { name: "Read.cv", url: "https://read.cv", category: "Career", description: "Profil profesional modern untuk kreator dan tech.", freeNote: "Gratis", suitableFor: "Profesional tech" },
  { name: "Wellfound", url: "https://wellfound.com", category: "Career", description: "Platform lowongan startup global.", freeNote: "Gratis", suitableFor: "Job seeker tech" },
  { name: "Remote OK", url: "https://remoteok.com", category: "Career", description: "Lowongan kerja remote dari berbagai perusahaan.", freeNote: "Gratis", suitableFor: "Pekerja remote" },

  { name: "Zapier", url: "https://zapier.com", category: "Productivity", description: "Automasi workflow antar aplikasi tanpa coding.", freeNote: "Free plan tersedia", suitableFor: "UMKM, tim operasional" },
  { name: "IFTTT", url: "https://ifttt.com", category: "Productivity", description: "Automasi sederhana berbasis trigger dan action.", freeNote: "Free plan terbatas", suitableFor: "Pengguna personal" },
  { name: "Milanote", url: "https://milanote.com", category: "Productivity", description: "Workspace visual untuk ide, riset, dan moodboard.", freeNote: "Free plan tersedia", suitableFor: "Kreator, product team" },
  { name: "Fibery", url: "https://fibery.io", category: "Productivity", description: "Gabungan docs, database, dan project management.", freeNote: "Trial tersedia", suitableFor: "Startup" },
  { name: "Heptabase", url: "https://heptabase.com", category: "Productivity", description: "Visual note-taking berbasis whiteboard card.", freeNote: "Trial tersedia", suitableFor: "Researcher" },
  { name: "Workflowy", url: "https://workflowy.com", category: "Productivity", description: "Outliner minimalis untuk catatan dan tugas.", freeNote: "Free plan tersedia", suitableFor: "Individu" },
  { name: "Taskade", url: "https://www.taskade.com", category: "Productivity", description: "To-do, dokumen, dan kolaborasi tim ringan.", freeNote: "Free plan tersedia", suitableFor: "Tim kecil" },
  { name: "TickTick", url: "https://ticktick.com", category: "Productivity", description: "Task manager dengan kalender dan habit tracker.", freeNote: "Free plan tersedia", suitableFor: "Produktivitas personal" },

  { name: "Datacamp", url: "https://www.datacamp.com", category: "Education", description: "Belajar data science dan analytics interaktif.", freeNote: "Sebagian materi gratis", suitableFor: "Calon data analyst" },
  { name: "GeeksforGeeks", url: "https://www.geeksforgeeks.org", category: "Education", description: "Materi DSA, coding interview, dan CS fundamentals.", freeNote: "Banyak konten gratis", suitableFor: "Mahasiswa TI" },
  { name: "Kaggle", url: "https://www.kaggle.com", category: "Education", description: "Kompetisi data, notebook, dan dataset pembelajaran.", freeNote: "Gratis", suitableFor: "Data enthusiast" },
  { name: "Scrimba", url: "https://scrimba.com", category: "Education", description: "Belajar coding lewat screencast interaktif.", freeNote: "Banyak materi gratis", suitableFor: "Pemula frontend" },
  { name: "CS50x", url: "https://cs50.harvard.edu/x", category: "Education", description: "Kelas computer science online yang populer.", freeNote: "Gratis", suitableFor: "Pemula coding" },
  { name: "NPTEL", url: "https://nptel.ac.in", category: "Education", description: "Kursus online dari institusi teknik dan sains.", freeNote: "Gratis", suitableFor: "Mahasiswa" },

  { name: "Fly.io", url: "https://fly.io", category: "Developer", description: "Deploy aplikasi dekat pengguna global dengan edge.", freeNote: "Free allowance tersedia", suitableFor: "Backend dev" },
  { name: "Koyeb", url: "https://www.koyeb.com", category: "Developer", description: "Platform deploy app dan API serverless.", freeNote: "Free tier tersedia", suitableFor: "Developer" },
  { name: "UptimeRobot", url: "https://uptimerobot.com", category: "Developer", description: "Monitoring uptime website dan endpoint.", freeNote: "Free plan tersedia", suitableFor: "DevOps, owner web" },
  { name: "Hop.io", url: "https://hop.io", category: "Developer", description: "Tunnel lokal untuk akses service development.", freeNote: "Free plan tersedia", suitableFor: "Backend dev" },
  { name: "Insomnia", url: "https://insomnia.rest", category: "Developer", description: "API client untuk testing REST, GraphQL, dan gRPC.", freeNote: "Free plan tersedia", suitableFor: "API developer" },
  { name: "Mockoon", url: "https://mockoon.com", category: "Developer", description: "Mock API lokal untuk pengembangan frontend.", freeNote: "Gratis", suitableFor: "Frontend, QA" },
  { name: "Squoosh", url: "https://squoosh.app", category: "Developer", description: "Kompres gambar untuk optimasi web.", freeNote: "Gratis", suitableFor: "Frontend dev" },
  { name: "Bundlephobia", url: "https://bundlephobia.com", category: "Developer", description: "Cek ukuran package npm sebelum dipakai.", freeNote: "Gratis", suitableFor: "JavaScript developer" },
  { name: "DevToys", url: "https://devtoys.app", category: "Developer", description: "Kumpulan utilitas developer dalam satu toolbox.", freeNote: "Gratis", suitableFor: "Developer" },

  { name: "Shots", url: "https://shots.so", category: "Design", description: "Buat mockup screenshot produk cepat.", freeNote: "Free plan tersedia", suitableFor: "Marketing, founder" },
  { name: "Haikei", url: "https://haikei.app", category: "Design", description: "Generator background SVG organik untuk UI.", freeNote: "Gratis", suitableFor: "UI designer" },
  { name: "BGJar", url: "https://bgjar.com", category: "Design", description: "Generator background pattern SVG siap pakai.", freeNote: "Gratis", suitableFor: "Designer, developer" },
  { name: "Iconoir", url: "https://iconoir.com", category: "Design", description: "Library ikon open-source yang konsisten.", freeNote: "Gratis", suitableFor: "Designer, dev" },
  { name: "Heroicons", url: "https://heroicons.com", category: "Design", description: "Set ikon gratis untuk produk digital.", freeNote: "Gratis", suitableFor: "Frontend dev" },
  { name: "Lucide", url: "https://lucide.dev", category: "Design", description: "Ikon open-source modern untuk antarmuka web.", freeNote: "Gratis", suitableFor: "UI engineer" },

  { name: "DocuSign", url: "https://www.docusign.com", category: "Utilities", description: "Tanda tangan dokumen digital secara online.", freeNote: "Trial tersedia", suitableFor: "Bisnis, legal" },
  { name: "Compress2Go", url: "https://www.compress2go.com", category: "Utilities", description: "Kompres file PDF, video, dan gambar online.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Clideo", url: "https://clideo.com", category: "Utilities", description: "Edit video ringan langsung dari browser.", freeNote: "Free dengan batasan", suitableFor: "Konten kreator" },
  { name: "Canva QR Generator", url: "https://www.canva.com/qr-code-generator", category: "Utilities", description: "Buat QR code cepat untuk tautan dan promosi.", freeNote: "Gratis", suitableFor: "UMKM" },
  { name: "Online OCR", url: "https://www.onlineocr.net", category: "Utilities", description: "Konversi gambar atau PDF ke teks editable.", freeNote: "Gratis dengan limit", suitableFor: "Admin, pelajar" },
  { name: "TeraBox", url: "https://www.terabox.com", category: "Utilities", description: "Cloud storage dengan kapasitas gratis besar.", freeNote: "Free plan tersedia", suitableFor: "Penyimpanan personal" },

  { name: "Plausible", url: "https://plausible.io", category: "Business", description: "Web analytics ringan dengan fokus privasi.", freeNote: "Trial tersedia", suitableFor: "Owner website" },
  { name: "Hotjar", url: "https://www.hotjar.com", category: "Business", description: "Heatmap dan rekaman perilaku pengguna website.", freeNote: "Free basic", suitableFor: "Product, UX" },
  { name: "Carrd Templates", url: "https://carrdtemplates.com", category: "Business", description: "Template landing page siap pakai untuk Carrd.", freeNote: "Banyak template gratis", suitableFor: "Founder, marketer" },
  { name: "Gumroad", url: "https://gumroad.com", category: "Business", description: "Jual produk digital langsung ke audiens.", freeNote: "Gratis daftar", suitableFor: "Creator" },
  { name: "Ko-fi", url: "https://ko-fi.com", category: "Business", description: "Terima dukungan dan jual konten kreator.", freeNote: "Gratis", suitableFor: "Kreator independen" },
  { name: "Lemon Squeezy", url: "https://www.lemonsqueezy.com", category: "Business", description: "Platform pembayaran untuk software dan produk digital.", freeNote: "Gratis daftar", suitableFor: "SaaS founder" },
  { name: "Bento", url: "https://bento.me", category: "Business", description: "Buat halaman link-in-bio untuk personal brand.", freeNote: "Gratis", suitableFor: "Creator" },

  { name: "Levels.fyi", url: "https://www.levels.fyi", category: "Career", description: "Data kompensasi dan level karier di perusahaan tech.", freeNote: "Gratis", suitableFor: "Software engineer" },
  { name: "Himalayas", url: "https://himalayas.app", category: "Career", description: "Lowongan remote dan profil perusahaan global.", freeNote: "Gratis", suitableFor: "Pekerja remote" },
  { name: "Remotive", url: "https://remotive.com", category: "Career", description: "Portal curated job remote berbagai bidang.", freeNote: "Gratis", suitableFor: "Remote worker" },
  { name: "Teal", url: "https://www.tealhq.com", category: "Career", description: "Job tracker dan alat optimasi pencarian kerja.", freeNote: "Free plan tersedia", suitableFor: "Job seeker" },

  { name: "Crontab Guru", url: "https://crontab.guru", category: "Developer", description: "Bantu membaca dan membuat ekspresi cron.", freeNote: "Gratis", suitableFor: "DevOps, backend" },
  { name: "JWT.io", url: "https://jwt.io", category: "Developer", description: "Decode dan verifikasi token JWT.", freeNote: "Gratis", suitableFor: "Backend dev" },

  { name: "ZeroTier", url: "https://www.zerotier.com", category: "Security", description: "Virtual network pribadi lintas perangkat.", freeNote: "Free plan tersedia", suitableFor: "Tim remote, homelab" },
  { name: "CryptPad", url: "https://cryptpad.fr", category: "Security", description: "Kolaborasi dokumen dengan enkripsi end-to-end.", freeNote: "Gratis", suitableFor: "Privasi tinggi" },
  { name: "OnionShare", url: "https://onionshare.org", category: "Security", description: "Berbagi file anonim lewat jaringan Tor.", freeNote: "Gratis", suitableFor: "Pengguna privasi" },

  { name: "Sleep Cycle", url: "https://www.sleepcycle.com", category: "Health", description: "Analisis kualitas tidur dan alarm pintar.", freeNote: "Free basic", suitableFor: "Produktivitas personal" },
  { name: "Strava", url: "https://www.strava.com", category: "Health", description: "Tracking aktivitas lari dan sepeda dengan komunitas.", freeNote: "Free plan tersedia", suitableFor: "Runner, cyclist" },
  { name: "JEFIT", url: "https://www.jefit.com", category: "Health", description: "Log latihan gym dan progres kebugaran.", freeNote: "Free plan tersedia", suitableFor: "Fitness enthusiast" },

  { name: "Slack", url: "https://slack.com", category: "Productivity", description: "Komunikasi tim dengan channel dan integrasi tools.", freeNote: "Free plan tersedia", suitableFor: "Tim startup" },
  { name: "Microsoft Teams", url: "https://www.microsoft.com/microsoft-teams", category: "Productivity", description: "Kolaborasi meeting, chat, dan dokumen dalam satu aplikasi.", freeNote: "Free plan tersedia", suitableFor: "Tim kerja" },
  { name: "Zoom", url: "https://zoom.us", category: "Productivity", description: "Video conference populer untuk meeting online.", freeNote: "Free plan tersedia", suitableFor: "Sekolah, bisnis" },
  { name: "Google Meet", url: "https://meet.google.com", category: "Productivity", description: "Meeting online cepat langsung dari ekosistem Google.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Calendar", url: "https://calendar.google.com", category: "Productivity", description: "Kalender digital untuk jadwal pribadi dan tim.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "Mural", url: "https://www.mural.co", category: "Productivity", description: "Whiteboard kolaboratif untuk workshop tim.", freeNote: "Free trial tersedia", suitableFor: "Product team" },
  { name: "Monday.com", url: "https://monday.com", category: "Productivity", description: "Work OS untuk manajemen proyek dan pipeline.", freeNote: "Trial tersedia", suitableFor: "Tim menengah" },
  { name: "Basecamp", url: "https://basecamp.com", category: "Productivity", description: "Kolaborasi proyek sederhana dan terpusat.", freeNote: "Trial tersedia", suitableFor: "Agency, tim remote" },

  { name: "Udemy", url: "https://www.udemy.com", category: "Education", description: "Marketplace kursus online berbagai topik profesional.", freeNote: "Sering ada kursus gratis/diskon", suitableFor: "Upskilling" },
  { name: "Skillshare", url: "https://www.skillshare.com", category: "Education", description: "Kursus kreatif untuk desain, bisnis, dan produktivitas.", freeNote: "Trial tersedia", suitableFor: "Kreator" },
  { name: "Pluralsight", url: "https://www.pluralsight.com", category: "Education", description: "Pembelajaran teknologi untuk developer dan IT.", freeNote: "Trial tersedia", suitableFor: "Profesional IT" },
  { name: "SoloLearn", url: "https://www.sololearn.com", category: "Education", description: "Belajar coding cepat via modul singkat dan komunitas.", freeNote: "Free plan tersedia", suitableFor: "Pemula" },
  { name: "Class Central", url: "https://www.classcentral.com", category: "Education", description: "Direktori kursus online dari berbagai platform global.", freeNote: "Gratis", suitableFor: "Pembelajar mandiri" },

  { name: "Bitbucket", url: "https://bitbucket.org", category: "Developer", description: "Hosting repository Git dengan integrasi Atlassian.", freeNote: "Free plan tersedia", suitableFor: "Dev team" },
  { name: "npm", url: "https://www.npmjs.com", category: "Developer", description: "Registry package JavaScript paling banyak digunakan.", freeNote: "Gratis", suitableFor: "JavaScript developer" },
  { name: "PyPI", url: "https://pypi.org", category: "Developer", description: "Repository package resmi untuk Python.", freeNote: "Gratis", suitableFor: "Python developer" },
  { name: "Docker Hub", url: "https://hub.docker.com", category: "Developer", description: "Registry image container untuk deployment dan testing.", freeNote: "Free tier tersedia", suitableFor: "DevOps, backend" },
  { name: "Kubernetes", url: "https://kubernetes.io", category: "Developer", description: "Dokumentasi dan ekosistem orkestrasi container.", freeNote: "Gratis", suitableFor: "DevOps engineer" },
  { name: "DigitalOcean", url: "https://www.digitalocean.com", category: "Developer", description: "Cloud platform populer untuk deploy aplikasi.", freeNote: "Trial credit tersedia", suitableFor: "Startup, developer" },
  { name: "Heroku", url: "https://www.heroku.com", category: "Developer", description: "Platform deployment aplikasi yang mudah digunakan.", freeNote: "Paket berbayar, dokumentasi gratis", suitableFor: "Pemula deploy" },
  { name: "Cloudflare", url: "https://www.cloudflare.com", category: "Developer", description: "CDN, DNS, dan keamanan website skala global.", freeNote: "Free plan tersedia", suitableFor: "Web owner, devops" },
  { name: "Firebase", url: "https://firebase.google.com", category: "Developer", description: "Backend-as-a-service untuk web dan mobile app.", freeNote: "Spark plan gratis", suitableFor: "Mobile dan web dev" },
  { name: "MongoDB Atlas", url: "https://www.mongodb.com/atlas", category: "Developer", description: "Managed database MongoDB di cloud.", freeNote: "Free tier tersedia", suitableFor: "Backend developer" },
  { name: "PlanetScale", url: "https://planetscale.com", category: "Developer", description: "MySQL serverless untuk aplikasi modern.", freeNote: "Free plan tersedia", suitableFor: "SaaS developer" },
  { name: "Neon", url: "https://neon.tech", category: "Developer", description: "Postgres serverless untuk workflow modern.", freeNote: "Free tier tersedia", suitableFor: "Backend developer" },
  { name: "OpenAPI", url: "https://www.openapis.org", category: "Developer", description: "Standar API specification yang banyak digunakan.", freeNote: "Gratis", suitableFor: "API architect" },
  { name: "Swagger", url: "https://swagger.io", category: "Developer", description: "Tooling populer untuk dokumentasi dan testing API.", freeNote: "Sebagian fitur gratis", suitableFor: "Backend dev" },
  { name: "Sentry", url: "https://sentry.io", category: "Developer", description: "Error monitoring dan performance tracking aplikasi.", freeNote: "Free plan tersedia", suitableFor: "Developer" },

  { name: "Adobe Color", url: "https://color.adobe.com", category: "Design", description: "Buat dan eksplorasi palet warna untuk brand/UI.", freeNote: "Gratis", suitableFor: "Designer" },
  { name: "Color Hunt", url: "https://colorhunt.co", category: "Design", description: "Inspirasi kombinasi warna siap pakai.", freeNote: "Gratis", suitableFor: "Designer" },
  { name: "Google Fonts", url: "https://fonts.google.com", category: "Design", description: "Koleksi font web gratis dan legal untuk komersial.", freeNote: "Gratis", suitableFor: "Web designer" },
  { name: "DaFont", url: "https://www.dafont.com", category: "Design", description: "Library font populer untuk berbagai kebutuhan desain.", freeNote: "Banyak font gratis", suitableFor: "Kreator" },
  { name: "Freepik", url: "https://www.freepik.com", category: "Design", description: "Aset desain seperti vektor, foto, dan PSD.", freeNote: "Free dengan atribusi", suitableFor: "Designer, marketer" },
  { name: "Storyset", url: "https://storyset.com", category: "Design", description: "Ilustrasi editable untuk presentasi dan web.", freeNote: "Gratis", suitableFor: "UI designer" },

  { name: "Google Translate", url: "https://translate.google.com", category: "Utilities", description: "Terjemahan teks dan dokumen lintas bahasa.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "DeepL", url: "https://www.deepl.com/translator", category: "Utilities", description: "Terjemahan otomatis dengan kualitas tinggi.", freeNote: "Free plan tersedia", suitableFor: "Profesional" },
  { name: "Canva Whiteboard", url: "https://www.canva.com/whiteboards", category: "Utilities", description: "Whiteboard visual untuk brainstorming cepat.", freeNote: "Free plan tersedia", suitableFor: "Tim kreatif" },
  { name: "WolframAlpha", url: "https://www.wolframalpha.com", category: "Utilities", description: "Mesin komputasi untuk matematika dan data.", freeNote: "Free plan tersedia", suitableFor: "Pelajar, peneliti" },
  { name: "Archive.org", url: "https://archive.org", category: "Utilities", description: "Arsip website, buku, dan media digital.", freeNote: "Gratis", suitableFor: "Peneliti, umum" },

  { name: "SEMrush", url: "https://www.semrush.com", category: "Business", description: "Tool SEO dan riset kompetitor yang banyak dipakai.", freeNote: "Trial tersedia", suitableFor: "Marketer" },
  { name: "Ahrefs", url: "https://ahrefs.com", category: "Business", description: "Platform SEO untuk analisis backlink dan keyword.", freeNote: "Webmaster tools gratis tersedia", suitableFor: "SEO specialist" },
  { name: "Mailchimp", url: "https://mailchimp.com", category: "Business", description: "Email marketing platform populer untuk bisnis.", freeNote: "Free plan tersedia", suitableFor: "UMKM" },
  { name: "Canva Business", url: "https://www.canva.com/teams", category: "Business", description: "Kolaborasi desain untuk tim marketing dan bisnis.", freeNote: "Free plan tersedia", suitableFor: "Tim konten" },
  { name: "Stripe", url: "https://stripe.com", category: "Business", description: "Infrastruktur pembayaran online untuk produk digital.", freeNote: "Gratis daftar", suitableFor: "SaaS, e-commerce" },
  { name: "PayPal", url: "https://www.paypal.com", category: "Business", description: "Pembayaran digital lintas negara yang luas dipakai.", freeNote: "Gratis daftar", suitableFor: "Freelancer, bisnis online" },
  { name: "Xero", url: "https://www.xero.com", category: "Business", description: "Akuntansi cloud untuk bisnis kecil menengah.", freeNote: "Trial tersedia", suitableFor: "UMKM" },

  { name: "Naukri", url: "https://www.naukri.com", category: "Career", description: "Portal lowongan kerja besar di Asia.", freeNote: "Gratis", suitableFor: "Pencari kerja" },
  { name: "Dice", url: "https://www.dice.com", category: "Career", description: "Portal kerja khusus profesional teknologi.", freeNote: "Gratis", suitableFor: "Tech talent" },
  { name: "AngelList Talent", url: "https://www.angellist.com/careers", category: "Career", description: "Akses karier startup dan perusahaan teknologi.", freeNote: "Gratis", suitableFor: "Startup job seeker" },

  { name: "1Password", url: "https://1password.com", category: "Security", description: "Password manager populer untuk individu dan tim.", freeNote: "Trial tersedia", suitableFor: "Privasi akun" },
  { name: "LastPass", url: "https://www.lastpass.com", category: "Security", description: "Manajemen password dan keamanan login.", freeNote: "Free plan tersedia", suitableFor: "Pengguna umum" },
  { name: "NordVPN", url: "https://nordvpn.com", category: "Security", description: "Layanan VPN populer untuk perlindungan koneksi.", freeNote: "Berbayar dengan trial/promo", suitableFor: "Pengguna internet" },
  { name: "ExpressVPN", url: "https://www.expressvpn.com", category: "Security", description: "VPN global untuk privasi dan keamanan jaringan.", freeNote: "Berbayar", suitableFor: "Pengguna privasi" },
  { name: "Malwarebytes", url: "https://www.malwarebytes.com", category: "Security", description: "Tool keamanan untuk deteksi malware dan ancaman.", freeNote: "Free scanner tersedia", suitableFor: "Pengguna PC" },

  { name: "Google Fit", url: "https://www.google.com/fit", category: "Health", description: "Pantau aktivitas fisik dan target kebugaran harian.", freeNote: "Gratis", suitableFor: "Pengguna Android" },
  { name: "Fitbit", url: "https://www.fitbit.com", category: "Health", description: "Tracking kesehatan dan aktivitas dari wearable.", freeNote: "Free basic", suitableFor: "Pengguna wearable" },
  { name: "Healthline", url: "https://www.healthline.com", category: "Health", description: "Artikel kesehatan populer yang mudah dipahami.", freeNote: "Gratis", suitableFor: "Umum" },
  { name: "WebMD", url: "https://www.webmd.com", category: "Health", description: "Informasi gejala dan topik kesehatan umum.", freeNote: "Gratis", suitableFor: "Umum" },

  { name: "NotebookLM", url: "https://notebooklm.google", category: "AI", description: "Asisten riset berbasis dokumen dari Google.", freeNote: "Free tier tersedia", suitableFor: "Mahasiswa, peneliti" },
  { name: "Midjourney", url: "https://www.midjourney.com", category: "AI", description: "Platform populer untuk generasi gambar AI.", freeNote: "Berbayar", suitableFor: "Kreator visual" },
  { name: "Runway", url: "https://runwayml.com", category: "AI", description: "Tool AI untuk pembuatan dan edit video kreatif.", freeNote: "Free plan tersedia", suitableFor: "Konten kreator" },
  { name: "Canva AI", url: "https://www.canva.com/magic-studio", category: "AI", description: "Fitur AI Canva untuk desain dan konten otomatis.", freeNote: "Free terbatas", suitableFor: "Marketing, creator" },
];

export const websiteCategories = [
  "All",
  ...new Set(websites.map((item) => item.category)),
];


