export type YouTubeChannel = {
  name: string;
  url: string;
  category: string;
  subscribers: string;
  description: string;
  language: string;
};

export const youtubeChannels: YouTubeChannel[] = [
  {
    name: "freeCodeCamp.org",
    url: "https://www.youtube.com/@freecodecamp",
    category: "Developer",
    subscribers: "11M+",
    description: "Tutorial programming lengkap dari beginner sampai advanced.",
    language: "English",
  },
  {
    name: "Traversy Media",
    url: "https://www.youtube.com/@TraversyMedia",
    category: "Developer",
    subscribers: "2.4M+",
    description: "Web development practical tutorial yang mudah diikuti.",
    language: "English",
  },
  {
    name: "Web Programming UNPAS",
    url: "https://www.youtube.com/@sandhikagalihWPU",
    category: "Developer",
    subscribers: "2.8M+",
    description: "Belajar web development dalam bahasa Indonesia.",
    language: "Indonesia",
  },
  {
    name: "Programming with Mosh",
    url: "https://www.youtube.com/@programmingwithmosh",
    category: "Developer",
    subscribers: "4.2M+",
    description: "Kursus coding terstruktur untuk karier software engineer.",
    language: "English",
  },
  {
    name: "Khan Academy",
    url: "https://www.youtube.com/@khanacademy",
    category: "Education",
    subscribers: "8M+",
    description: "Materi edukasi matematika, sains, ekonomi, dan lainnya.",
    language: "English",
  },
  {
    name: "TED-Ed",
    url: "https://www.youtube.com/@TEDEd",
    category: "Education",
    subscribers: "21M+",
    description: "Video edukasi animasi dengan topik pengetahuan umum.",
    language: "English",
  },
  {
    name: "CrashCourse",
    url: "https://www.youtube.com/@crashcourse",
    category: "Education",
    subscribers: "16M+",
    description: "Seri pembelajaran cepat untuk berbagai disiplin ilmu.",
    language: "English",
  },
  {
    name: "Ruangguru",
    url: "https://www.youtube.com/@ruanggurucom",
    category: "Education",
    subscribers: "1M+",
    description: "Konten belajar untuk pelajar Indonesia.",
    language: "Indonesia",
  },
  {
    name: "Canva",
    url: "https://www.youtube.com/@Canva",
    category: "Design",
    subscribers: "1M+",
    description: "Tips desain dan konten visual untuk creator.",
    language: "English",
  },
  {
    name: "The Futur",
    url: "https://www.youtube.com/@thefutur",
    category: "Design",
    subscribers: "2.4M+",
    description: "Branding, desain, dan bisnis kreatif.",
    language: "English",
  },
  {
    name: "Piximperfect",
    url: "https://www.youtube.com/@PiXimperfect",
    category: "Design",
    subscribers: "4.8M+",
    description: "Tutorial Photoshop detail dan teknik profesional.",
    language: "English",
  },
  {
    name: "Thomas Frank",
    url: "https://www.youtube.com/@Thomasfrank",
    category: "Productivity",
    subscribers: "3M+",
    description: "Produktivitas, sistem belajar, dan personal growth.",
    language: "English",
  },
  {
    name: "Ali Abdaal",
    url: "https://www.youtube.com/@aliabdaal",
    category: "Productivity",
    subscribers: "6M+",
    description: "Produktivitas, career tips, dan creator workflow.",
    language: "English",
  },
  {
    name: "Nihongo Mantappu",
    url: "https://www.youtube.com/@NihongoMantappu",
    category: "Productivity",
    subscribers: "10M+",
    description: "Edukasi, budaya, dan motivasi belajar untuk Gen Z.",
    language: "Indonesia",
  },
  {
    name: "Huberman Lab",
    url: "https://www.youtube.com/@hubermanlab",
    category: "Health",
    subscribers: "6M+",
    description: "Neuroscience untuk tidur, fokus, dan performa tubuh.",
    language: "English",
  },
  {
    name: "Athlean-X",
    url: "https://www.youtube.com/@ATHLEANX",
    category: "Health",
    subscribers: "14M+",
    description: "Latihan kebugaran berbasis ilmu anatomi dan performa.",
    language: "English",
  },
  {
    name: "Pamela Reif",
    url: "https://www.youtube.com/@PamelaRf1",
    category: "Health",
    subscribers: "10M+",
    description: "Workout rumahan tanpa alat dengan video terstruktur.",
    language: "English",
  },
  {
    name: "GaryVee",
    url: "https://www.youtube.com/@garyvee",
    category: "Business",
    subscribers: "4.5M+",
    description: "Marketing, entrepreneurship, dan personal branding.",
    language: "English",
  },
  {
    name: "Valuetainment",
    url: "https://www.youtube.com/@VALUETAINMENT",
    category: "Business",
    subscribers: "6M+",
    description: "Leadership, strategi bisnis, dan wawancara entrepreneur.",
    language: "English",
  },
  {
    name: "Andhika Diskartes",
    url: "https://www.youtube.com/@AndhikaDiskartes",
    category: "Business",
    subscribers: "1M+",
    description: "Insight bisnis, karier, dan mindset profesional.",
    language: "Indonesia",
  },
  {
    name: "Two Minute Papers",
    url: "https://www.youtube.com/@TwoMinutePapers",
    category: "AI",
    subscribers: "1.7M+",
    description: "Update riset AI dengan penjelasan ringan.",
    language: "English",
  },
  {
    name: "DeepLearningAI",
    url: "https://www.youtube.com/@Deeplearningai",
    category: "AI",
    subscribers: "1.1M+",
    description: "Tutorial AI practical dan learning resources.",
    language: "English",
  },
  {
    name: "ColdFusion",
    url: "https://www.youtube.com/@ColdFusion",
    category: "AI",
    subscribers: "5M+",
    description: "Teknologi dan inovasi AI dalam narasi dokumenter.",
    language: "English",
  },
  {
    name: "NetworkChuck",
    url: "https://www.youtube.com/@NetworkChuck",
    category: "Security",
    subscribers: "4.5M+",
    description: "Cybersecurity, networking, dan hands-on labs.",
    language: "English",
  },
  {
    name: "John Hammond",
    url: "https://www.youtube.com/@_JohnHammond",
    category: "Security",
    subscribers: "1.5M+",
    description: "CTF, ethical hacking, dan incident analysis.",
    language: "English",
  },
  {
    name: "The Cyber Mentor",
    url: "https://www.youtube.com/@TCMSecurityAcademy",
    category: "Security",
    subscribers: "1M+",
    description: "Belajar ethical hacking dari nol.",
    language: "English",
  },
  {
    name: "LinkedIn",
    url: "https://www.youtube.com/@LinkedIn",
    category: "Career",
    subscribers: "2M+",
    description: "Tips karier, interview, dan pengembangan profesional.",
    language: "English",
  },
  {
    name: "Life at Google",
    url: "https://www.youtube.com/@LifeatGoogle",
    category: "Career",
    subscribers: "1.1M+",
    description: "Career advice dan insight dunia kerja tech.",
    language: "English",
  },
  {
    name: "Self Made Millennial",
    url: "https://www.youtube.com/@SelfMadeMillennial",
    category: "Career",
    subscribers: "1.3M+",
    description: "Interview, CV, dan strategi dapat kerja.",
    language: "English",
  },
  {
    name: "Kevin Stratvert",
    url: "https://www.youtube.com/@KevinStratvert",
    category: "Utilities",
    subscribers: "2.7M+",
    description: "Tips aplikasi office, productivity tools, dan software.",
    language: "English",
  },
  {
    name: "ExcelIsFun",
    url: "https://www.youtube.com/@excelisfun",
    category: "Utilities",
    subscribers: "1.3M+",
    description: "Tutorial Excel komprehensif untuk kerja harian.",
    language: "English",
  },
  {
    name: "Howfinity",
    url: "https://www.youtube.com/@Howfinity",
    category: "Utilities",
    subscribers: "1.2M+",
    description: "Tutorial aplikasi online, web tools, dan workflow.",
    language: "English",
  },
  {
    name: "Jess No Limit",
    url: "https://www.youtube.com/@JessNoLimit",
    category: "Utilities",
    subscribers: "52M+",
    description: "Channel Indonesia populer dengan konten hiburan digital.",
    language: "Indonesia",
  },
];
