export type YouTubeChannel = {
  name: string;
  url: string;
  category: string;
  subscribers: string;
  description: string;
  language: string;
};

export const youtubeChannels: YouTubeChannel[] = [
  {
    name: "freeCodeCamp.org",
    url: "https://www.youtube.com/@freecodecamp",
    category: "Developer",
    subscribers: "11M+",
    description: "Tutorial programming lengkap dari beginner sampai advanced.",
    language: "English",
  },
  {
    name: "Traversy Media",
    url: "https://www.youtube.com/@TraversyMedia",
    category: "Developer",
    subscribers: "2.4M+",
    description: "Web development practical tutorial yang mudah diikuti.",
    language: "English",
  },
  {
    name: "Web Programming UNPAS",
    url: "https://www.youtube.com/@sandhikagalihWPU",
    category: "Developer",
    subscribers: "2.8M+",
    description: "Belajar web development dalam bahasa Indonesia.",
    language: "Indonesia",
  },
  {
    name: "Programming with Mosh",
    url: "https://www.youtube.com/@programmingwithmosh",
    category: "Developer",
    subscribers: "4.2M+",
    description: "Kursus coding terstruktur untuk karier software engineer.",
    language: "English",
  },
  {
    name: "Khan Academy",
    url: "https://www.youtube.com/@khanacademy",
    category: "Education",
    subscribers: "8M+",
    description: "Materi edukasi matematika, sains, ekonomi, dan lainnya.",
    language: "English",
  },
  {
    name: "TED-Ed",
    url: "https://www.youtube.com/@TEDEd",
    category: "Education",
    subscribers: "21M+",
    description: "Video edukasi animasi dengan topik pengetahuan umum.",
    language: "English",
  },
  {
    name: "CrashCourse",
    url: "https://www.youtube.com/@crashcourse",
    category: "Education",
    subscribers: "16M+",
    description: "Seri pembelajaran cepat untuk berbagai disiplin ilmu.",
    language: "English",
  },
  {
    name: "Ruangguru",
    url: "https://www.youtube.com/@ruanggurucom",
    category: "Education",
    subscribers: "1M+",
    description: "Konten belajar untuk pelajar Indonesia.",
    language: "Indonesia",
  },
  {
    name: "Canva",
    url: "https://www.youtube.com/@Canva",
    category: "Design",
    subscribers: "1M+",
    description: "Tips desain dan konten visual untuk creator.",
    language: "English",
  },
  {
    name: "The Futur",
    url: "https://www.youtube.com/@thefutur",
    category: "Design",
    subscribers: "2.4M+",
    description: "Branding, desain, dan bisnis kreatif.",
    language: "English",
  },
  {
    name: "Piximperfect",
    url: "https://www.youtube.com/@PiXimperfect",
    category: "Design",
    subscribers: "4.8M+",
    description: "Tutorial Photoshop detail dan teknik profesional.",
    language: "English",
  },
  {
    name: "Thomas Frank",
    url: "https://www.youtube.com/@Thomasfrank",
    category: "Productivity",
    subscribers: "3M+",
    description: "Produktivitas, sistem belajar, dan personal growth.",
    language: "English",
  },
  {
    name: "Ali Abdaal",
    url: "https://www.youtube.com/@aliabdaal",
    category: "Productivity",
    subscribers: "6M+",
    description: "Produktivitas, career tips, dan creator workflow.",
    language: "English",
  },
  {
    name: "Nihongo Mantappu",
    url: "https://www.youtube.com/@NihongoMantappu",
    category: "Productivity",
    subscribers: "10M+",
    description: "Edukasi, budaya, dan motivasi belajar untuk Gen Z.",
    language: "Indonesia",
  },
  {
    name: "Huberman Lab",
    url: "https://www.youtube.com/@hubermanlab",
    category: "Health",
    subscribers: "6M+",
    description: "Neuroscience untuk tidur, fokus, dan performa tubuh.",
    language: "English",
  },
  {
    name: "Athlean-X",
    url: "https://www.youtube.com/@ATHLEANX",
    category: "Health",
    subscribers: "14M+",
    description: "Latihan kebugaran berbasis ilmu anatomi dan performa.",
    language: "English",
  },
  {
    name: "Pamela Reif",
    url: "https://www.youtube.com/@PamelaRf1",
    category: "Health",
    subscribers: "10M+",
    description: "Workout rumahan tanpa alat dengan video terstruktur.",
    language: "English",
  },
  {
    name: "GaryVee",
    url: "https://www.youtube.com/@garyvee",
    category: "Business",
    subscribers: "4.5M+",
    description: "Marketing, entrepreneurship, dan personal branding.",
    language: "English",
  },
  {
    name: "Valuetainment",
    url: "https://www.youtube.com/@VALUETAINMENT",
    category: "Business",
    subscribers: "6M+",
    description: "Leadership, strategi bisnis, dan wawancara entrepreneur.",
    language: "English",
  },
  {
    name: "Andhika Diskartes",
    url: "https://www.youtube.com/@AndhikaDiskartes",
    category: "Business",
    subscribers: "1M+",
    description: "Insight bisnis, karier, dan mindset profesional.",
    language: "Indonesia",
  },
  {
    name: "Two Minute Papers",
    url: "https://www.youtube.com/@TwoMinutePapers",
    category: "AI",
    subscribers: "1.7M+",
    description: "Update riset AI dengan penjelasan ringan.",
    language: "English",
  },
  {
    name: "DeepLearningAI",
    url: "https://www.youtube.com/@Deeplearningai",
    category: "AI",
    subscribers: "1.1M+",
    description: "Tutorial AI practical dan learning resources.",
    language: "English",
  },
  {
    name: "ColdFusion",
    url: "https://www.youtube.com/@ColdFusion",
    category: "AI",
    subscribers: "5M+",
    description: "Teknologi dan inovasi AI dalam narasi dokumenter.",
    language: "English",
  },
  {
    name: "NetworkChuck",
    url: "https://www.youtube.com/@NetworkChuck",
    category: "Security",
    subscribers: "4.5M+",
    description: "Cybersecurity, networking, dan hands-on labs.",
    language: "English",
  },
  {
    name: "John Hammond",
    url: "https://www.youtube.com/@_JohnHammond",
    category: "Security",
    subscribers: "1.5M+",
    description: "CTF, ethical hacking, dan incident analysis.",
    language: "English",
  },
  {
    name: "The Cyber Mentor",
    url: "https://www.youtube.com/@TCMSecurityAcademy",
    category: "Security",
    subscribers: "1M+",
    description: "Belajar ethical hacking dari nol.",
    language: "English",
  },
  {
    name: "LinkedIn",
    url: "https://www.youtube.com/@LinkedIn",
    category: "Career",
    subscribers: "2M+",
    description: "Tips karier, interview, dan pengembangan profesional.",
    language: "English",
  },
  {
    name: "Life at Google",
    url: "https://www.youtube.com/@LifeatGoogle",
    category: "Career",
    subscribers: "1.1M+",
    description: "Career advice dan insight dunia kerja tech.",
    language: "English",
  },
  {
    name: "Self Made Millennial",
    url: "https://www.youtube.com/@SelfMadeMillennial",
    category: "Career",
    subscribers: "1.3M+",
    description: "Interview, CV, dan strategi dapat kerja.",
    language: "English",
  },
  {
    name: "Kevin Stratvert",
    url: "https://www.youtube.com/@KevinStratvert",
    category: "Utilities",
    subscribers: "2.7M+",
    description: "Tips aplikasi office, productivity tools, dan software.",
    language: "English",
  },
  {
    name: "ExcelIsFun",
    url: "https://www.youtube.com/@excelisfun",
    category: "Utilities",
    subscribers: "1.3M+",
    description: "Tutorial Excel komprehensif untuk kerja harian.",
    language: "English",
  },
  {
    name: "Howfinity",
    url: "https://www.youtube.com/@Howfinity",
    category: "Utilities",
    subscribers: "1.2M+",
    description: "Tutorial aplikasi online, web tools, dan workflow.",
    language: "English",
  },
  {
    name: "Jess No Limit",
    url: "https://www.youtube.com/@JessNoLimit",
    category: "Utilities",
    subscribers: "52M+",
    description: "Channel Indonesia populer dengan konten hiburan digital.",
    language: "Indonesia",
  },
  {
    name: "Fireship",
    url: "https://www.youtube.com/@Fireship",
    category: "Developer",
    subscribers: "3M+",
    description: "Update cepat dunia software engineering dan web development.",
    language: "English",
  },
  {
    name: "The Net Ninja",
    url: "https://www.youtube.com/@NetNinja",
    category: "Developer",
    subscribers: "1.6M+",
    description: "Playlist coding terstruktur untuk web, backend, dan framework modern.",
    language: "English",
  },
  {
    name: "Academind",
    url: "https://www.youtube.com/@academind",
    category: "Developer",
    subscribers: "1M+",
    description: "Tutorial JavaScript, React, dan backend dengan penjelasan detail.",
    language: "English",
  },
  {
    name: "CodeWithHarry",
    url: "https://www.youtube.com/@CodeWithHarry",
    category: "Developer",
    subscribers: "7M+",
    description: "Belajar programming dari dasar dengan materi yang sangat lengkap.",
    language: "Hindi/English",
  },
  {
    name: "Bro Code",
    url: "https://www.youtube.com/@BroCodez",
    category: "Developer",
    subscribers: "2M+",
    description: "Tutorial coding praktis dan ringkas untuk pemula.",
    language: "English",
  },
  {
    name: "Tech With Tim",
    url: "https://www.youtube.com/@TechWithTim",
    category: "Developer",
    subscribers: "2M+",
    description: "Konten Python, AI, dan software project-based.",
    language: "English",
  },
  {
    name: "Apna College",
    url: "https://www.youtube.com/@ApnaCollegeOfficial",
    category: "Developer",
    subscribers: "7M+",
    description: "Materi DSA, placement prep, dan web development.",
    language: "Hindi/English",
  },
  {
    name: "Telusko",
    url: "https://www.youtube.com/@Telusko",
    category: "Developer",
    subscribers: "2.5M+",
    description: "Tutorial Java, Spring, dan konsep software engineering.",
    language: "English",
  },
  {
    name: "Nas Daily",
    url: "https://www.youtube.com/@NasDaily",
    category: "Education",
    subscribers: "16M+",
    description: "Video edukasi singkat tentang budaya, sains, dan insight global.",
    language: "English",
  },
  {
    name: "Veritasium",
    url: "https://www.youtube.com/@veritasium",
    category: "Education",
    subscribers: "17M+",
    description: "Eksplorasi sains dan fenomena dunia dengan eksperimen menarik.",
    language: "English",
  },
  {
    name: "Vsauce",
    url: "https://www.youtube.com/@Vsauce",
    category: "Education",
    subscribers: "22M+",
    description: "Pertanyaan sains dan filosofi dijelaskan dengan cara unik.",
    language: "English",
  },
  {
    name: "Kurzgesagt - In a Nutshell",
    url: "https://www.youtube.com/@kurzgesagt",
    category: "Education",
    subscribers: "24M+",
    description: "Animasi edukasi berkualitas tinggi tentang sains dan masa depan.",
    language: "English",
  },
  {
    name: "Bright Side",
    url: "https://www.youtube.com/@BRIGHTSIDEOFFICIAL",
    category: "Education",
    subscribers: "45M+",
    description: "Fakta menarik, tips, dan konten pengetahuan umum.",
    language: "English",
  },
  {
    name: "Marques Brownlee",
    url: "https://www.youtube.com/@mkbhd",
    category: "Utilities",
    subscribers: "20M+",
    description: "Review gadget, AI, dan teknologi dengan produksi premium.",
    language: "English",
  },
  {
    name: "Mrwhosetheboss",
    url: "https://www.youtube.com/@Mrwhosetheboss",
    category: "Utilities",
    subscribers: "20M+",
    description: "Review smartphone, aplikasi, dan tren teknologi populer.",
    language: "English",
  },
  {
    name: "Tech Burner",
    url: "https://www.youtube.com/@TechBurner",
    category: "Utilities",
    subscribers: "14M+",
    description: "Konten teknologi dan gadget dengan gaya ringan dan menarik.",
    language: "Hindi",
  },
  {
    name: "UrAvgConsumer",
    url: "https://www.youtube.com/@UrAvgConsumer",
    category: "Utilities",
    subscribers: "3M+",
    description: "Review perangkat dan setup teknologi untuk pengguna harian.",
    language: "English",
  },
  {
    name: "Matt D'Avella",
    url: "https://www.youtube.com/@mattdavella",
    category: "Productivity",
    subscribers: "4M+",
    description: "Produktivitas, kebiasaan, dan gaya hidup minimalis.",
    language: "English",
  },
  {
    name: "Mufti Menk",
    url: "https://www.youtube.com/@muftimenkofficial",
    category: "Productivity",
    subscribers: "5M+",
    description: "Motivasi dan pengembangan diri dengan pesan positif.",
    language: "English",
  },
  {
    name: "Sandeep Maheshwari",
    url: "https://www.youtube.com/@SandeepSeminars",
    category: "Productivity",
    subscribers: "28M+",
    description: "Motivasi, mindset, dan pengembangan diri untuk karier.",
    language: "Hindi",
  },
  {
    name: "Graham Stephan",
    url: "https://www.youtube.com/@GrahamStephan",
    category: "Business",
    subscribers: "5M+",
    description: "Edukasi finansial, investasi, dan strategi bisnis personal.",
    language: "English",
  },
  {
    name: "Erika Kullberg",
    url: "https://www.youtube.com/@ErikaKullberg",
    category: "Business",
    subscribers: "11M+",
    description: "Tips legal, keuangan, dan perlindungan konsumen.",
    language: "English",
  },
  {
    name: "Alex Hormozi",
    url: "https://www.youtube.com/@AlexHormozi",
    category: "Business",
    subscribers: "3M+",
    description: "Strategi pertumbuhan bisnis dan penjualan berbasis praktik.",
    language: "English",
  },
  {
    name: "Simplilearn",
    url: "https://www.youtube.com/@SimplilearnOfficial",
    category: "AI",
    subscribers: "5M+",
    description: "Konten upskilling data, cloud, dan AI untuk profesional.",
    language: "English",
  },
  {
    name: "Krish Naik",
    url: "https://www.youtube.com/@krishnaik06",
    category: "AI",
    subscribers: "1.2M+",
    description: "Machine learning dan data science dengan pendekatan praktis.",
    language: "English",
  },
  {
    name: "Sentdex",
    url: "https://www.youtube.com/@sentdex",
    category: "AI",
    subscribers: "1.5M+",
    description: "Tutorial Python untuk ML, data analysis, dan automation.",
    language: "English",
  },
  {
    name: "Doctor Mike",
    url: "https://www.youtube.com/@DoctorMike",
    category: "Health",
    subscribers: "14M+",
    description: "Edukasi kesehatan dan kebugaran berbasis medis.",
    language: "English",
  },
  {
    name: "Yoga With Adriene",
    url: "https://www.youtube.com/@yogawithadriene",
    category: "Health",
    subscribers: "13M+",
    description: "Latihan yoga gratis untuk pemula hingga lanjutan.",
    language: "English",
  },
  {
    name: "Fraser",
    url: "https://www.youtube.com/@Fraser",
    category: "Career",
    subscribers: "2M+",
    description: "Tips karier, personal branding, dan pengembangan profesional.",
    language: "English",
  },
  {
    name: "Andrew Lacivita",
    url: "https://www.youtube.com/@andylacivita",
    category: "Career",
    subscribers: "1.4M+",
    description: "Strategi interview, CV, dan negosiasi karier.",
    language: "English",
  },
  {
    name: "David Bombal",
    url: "https://www.youtube.com/@davidbombal",
    category: "Security",
    subscribers: "2.5M+",
    description: "Cybersecurity, networking, dan ethical hacking untuk praktisi.",
    language: "English",
  },
  {
    name: "LiveOverflow",
    url: "https://www.youtube.com/@LiveOverflow",
    category: "Security",
    subscribers: "2M+",
    description: "Eksplorasi bug bounty, exploit, dan keamanan aplikasi.",
    language: "English",
  },
  {
    name: "Corey Schafer",
    url: "https://www.youtube.com/@coreyms",
    category: "Developer",
    subscribers: "1.4M+",
    description: "Tutorial Python berkualitas tinggi untuk backend dan automasi.",
    language: "English",
  },
  {
    name: "Derek Banas",
    url: "https://www.youtube.com/@derekbanas",
    category: "Developer",
    subscribers: "1.3M+",
    description: "Belajar banyak bahasa pemrograman dengan format ringkas.",
    language: "English",
  },
  {
    name: "CodeBeauty",
    url: "https://www.youtube.com/@CodeBeauty",
    category: "Developer",
    subscribers: "1.2M+",
    description: "Tutorial JavaScript dan React untuk pemula hingga menengah.",
    language: "English",
  },
  {
    name: "National Geographic",
    url: "https://www.youtube.com/@NatGeo",
    category: "Education",
    subscribers: "24M+",
    description: "Konten dokumenter edukatif tentang sains, alam, dan budaya.",
    language: "English",
  },
  {
    name: "Big Think",
    url: "https://www.youtube.com/@bigthink",
    category: "Education",
    subscribers: "7M+",
    description: "Insight sains, psikologi, dan ide besar dari para ahli.",
    language: "English",
  },
  {
    name: "SciShow",
    url: "https://www.youtube.com/@SciShow",
    category: "Education",
    subscribers: "8M+",
    description: "Penjelasan topik sains dengan format ringan dan informatif.",
    language: "English",
  },
  {
    name: "AsapSCIENCE",
    url: "https://www.youtube.com/@AsapSCIENCE",
    category: "Education",
    subscribers: "10M+",
    description: "Animasi edukasi sains dan kesehatan dengan gaya sederhana.",
    language: "English",
  },
  {
    name: "Linus Tech Tips",
    url: "https://www.youtube.com/@LinusTechTips",
    category: "Utilities",
    subscribers: "16M+",
    description: "Review hardware, teknologi, dan tips setup perangkat.",
    language: "English",
  },
  {
    name: "Unbox Therapy",
    url: "https://www.youtube.com/@unboxtherapy",
    category: "Utilities",
    subscribers: "24M+",
    description: "Ulasan gadget populer dan tren teknologi terbaru.",
    language: "English",
  },
  {
    name: "Satori Graphics",
    url: "https://www.youtube.com/@SatoriGraphics",
    category: "Design",
    subscribers: "1.4M+",
    description: "Tutorial branding, layout, dan desain grafis praktis.",
    language: "English",
  },
  {
    name: "Will Paterson",
    url: "https://www.youtube.com/@willpatersondesign",
    category: "Design",
    subscribers: "1.6M+",
    description: "Tips logo design, kritik karya, dan workflow desainer.",
    language: "English",
  },
  {
    name: "Think Media",
    url: "https://www.youtube.com/@ThinkMediaTV",
    category: "Business",
    subscribers: "3M+",
    description: "Strategi konten, growth channel, dan monetisasi creator.",
    language: "English",
  },
  {
    name: "Simon Squibb",
    url: "https://www.youtube.com/@SimonSquibb",
    category: "Business",
    subscribers: "2M+",
    description: "Motivasi entrepreneurship dan strategi membangun bisnis.",
    language: "English",
  },
  {
    name: "Noah Kagan",
    url: "https://www.youtube.com/@noahkagan",
    category: "Business",
    subscribers: "1.1M+",
    description: "Eksperimen bisnis, marketing, dan growth untuk founder.",
    language: "English",
  },
  {
    name: "Matt Wolfe",
    url: "https://www.youtube.com/@mreflow",
    category: "AI",
    subscribers: "1.1M+",
    description: "Update tools AI terbaru untuk produktivitas dan kreator.",
    language: "English",
  },
  {
    name: "All About AI",
    url: "https://www.youtube.com/@AllAboutAI",
    category: "AI",
    subscribers: "1M+",
    description: "Tutorial pemanfaatan AI untuk kerja dan bisnis digital.",
    language: "English",
  },
  {
    name: "Hak5",
    url: "https://www.youtube.com/@Hak5",
    category: "Security",
    subscribers: "1.2M+",
    description: "Cybersecurity tools, pentest workflow, dan eksperimen jaringan.",
    language: "English",
  },
  {
    name: "Loi Liang Yang",
    url: "https://www.youtube.com/@LoiLiangYang",
    category: "Security",
    subscribers: "1.1M+",
    description: "Konten cyber security praktis untuk beginner hingga intermediate.",
    language: "English",
  },
  {
    name: "Chloe Ting",
    url: "https://www.youtube.com/@ChloeTing",
    category: "Health",
    subscribers: "25M+",
    description: "Program workout rumahan dengan challenge yang terstruktur.",
    language: "English",
  },
  {
    name: "MadFit",
    url: "https://www.youtube.com/@MadFit",
    category: "Health",
    subscribers: "10M+",
    description: "Latihan fitness harian untuk kekuatan dan pembakaran kalori.",
    language: "English",
  },
  {
    name: "Improvement Pill",
    url: "https://www.youtube.com/@ImprovementPillChannel",
    category: "Productivity",
    subscribers: "3M+",
    description: "Self-improvement dan kebiasaan produktif dengan visual animasi.",
    language: "English",
  },
  {
    name: "Better Ideas",
    url: "https://www.youtube.com/@BetterIdeas",
    category: "Productivity",
    subscribers: "2M+",
    description: "Produktivitas, disiplin, dan mindset kerja kreatif.",
    language: "English",
  },
  {
    name: "Kok Bisa?",
    url: "https://www.youtube.com/@kokbisa",
    category: "Education",
    subscribers: "4M+",
    description: "Konten edukasi sains dan sosial dalam bahasa Indonesia.",
    language: "Indonesia",
  },
  {
    name: "Kelas Terbuka",
    url: "https://www.youtube.com/@kelasterbuka",
    category: "Developer",
    subscribers: "1M+",
    description: "Belajar coding dan computer science dalam bahasa Indonesia.",
    language: "Indonesia",
  },
  {
    name: "CS Dojo",
    url: "https://www.youtube.com/@CSDojo",
    category: "Developer",
    subscribers: "1.9M+",
    description: "Materi coding interview dan algoritma untuk software engineer.",
    language: "English",
  },
  {
    name: "ProgrammingKnowledge",
    url: "https://www.youtube.com/@ProgrammingKnowledge",
    category: "Developer",
    subscribers: "1.9M+",
    description: "Tutorial bahasa pemrograman dari dasar hingga aplikasi nyata.",
    language: "English",
  },
  {
    name: "Clever Programmer",
    url: "https://www.youtube.com/@CleverProgrammer",
    category: "Developer",
    subscribers: "1.3M+",
    description: "Belajar membuat project software dengan pendekatan praktis.",
    language: "English",
  },
  {
    name: "Thapa Technical",
    url: "https://www.youtube.com/@ThapaTechnical",
    category: "Developer",
    subscribers: "2M+",
    description: "Tutorial web development lengkap untuk pemula dan menengah.",
    language: "Hindi",
  },
  {
    name: "Amigoscode",
    url: "https://www.youtube.com/@amigoscode",
    category: "Developer",
    subscribers: "1.6M+",
    description: "Konten Java, Spring Boot, dan backend engineering.",
    language: "English",
  },

  {
    name: "TEDx Talks",
    url: "https://www.youtube.com/@TEDx",
    category: "Education",
    subscribers: "41M+",
    description: "Talk inspiratif dari pakar lintas bidang dan disiplin.",
    language: "English",
  },
  {
    name: "BBC Earth",
    url: "https://www.youtube.com/@BBCEarth",
    category: "Education",
    subscribers: "13M+",
    description: "Dokumenter alam dan sains dengan visual berkualitas tinggi.",
    language: "English",
  },
  {
    name: "Vox",
    url: "https://www.youtube.com/@Vox",
    category: "Education",
    subscribers: "13M+",
    description: "Penjelasan isu dunia, sains, dan budaya secara visual.",
    language: "English",
  },
  {
    name: "DW Documentary",
    url: "https://www.youtube.com/@DWDocumentary",
    category: "Education",
    subscribers: "6M+",
    description: "Dokumenter mendalam tentang isu global dan teknologi.",
    language: "English",
  },
  {
    name: "RealLifeLore",
    url: "https://www.youtube.com/@RealLifeLore",
    category: "Education",
    subscribers: "8M+",
    description: "Geopolitik, sains, dan pengetahuan umum dengan storytelling.",
    language: "English",
  },
  {
    name: "SmarterEveryDay",
    url: "https://www.youtube.com/@smartereveryday",
    category: "Education",
    subscribers: "11M+",
    description: "Eksperimen sains dan engineering dengan pendekatan menarik.",
    language: "English",
  },
  {
    name: "MinutePhysics",
    url: "https://www.youtube.com/@MinutePhysics",
    category: "Education",
    subscribers: "6M+",
    description: "Konsep fisika dijelaskan singkat dan mudah dipahami.",
    language: "English",
  },
  {
    name: "CGP Grey",
    url: "https://www.youtube.com/@CGPGrey",
    category: "Education",
    subscribers: "6M+",
    description: "Penjelasan sistem, sejarah, dan konsep kompleks secara ringkas.",
    language: "English",
  },

  {
    name: "GFXMentor",
    url: "https://www.youtube.com/@GFXMentor",
    category: "Design",
    subscribers: "4M+",
    description: "Tutorial desain grafis, Photoshop, dan Illustrator untuk pemula.",
    language: "Urdu/Hindi",
  },
  {
    name: "tutvid",
    url: "https://www.youtube.com/@tutvid",
    category: "Design",
    subscribers: "1.3M+",
    description: "Teknik desain visual dan editing untuk kreator digital.",
    language: "English",
  },
  {
    name: "Envato Tuts+",
    url: "https://www.youtube.com/@envatotutsplus",
    category: "Design",
    subscribers: "1.4M+",
    description: "Tutorial desain, video, dan workflow kreatif profesional.",
    language: "English",
  },

  {
    name: "Lavendaire",
    url: "https://www.youtube.com/@lavendaire",
    category: "Productivity",
    subscribers: "2M+",
    description: "Konten self-growth, journaling, dan produktivitas mindful.",
    language: "English",
  },
  {
    name: "Jeff Su",
    url: "https://www.youtube.com/@JeffSu",
    category: "Productivity",
    subscribers: "2M+",
    description: "Tips produktivitas kerja, komunikasi, dan karier modern.",
    language: "English",
  },
  {
    name: "Better Than Yesterday",
    url: "https://www.youtube.com/@bettertanyesterday",
    category: "Productivity",
    subscribers: "1.8M+",
    description: "Video pengembangan diri berbasis kebiasaan dan disiplin.",
    language: "English",
  },

  {
    name: "CNBC",
    url: "https://www.youtube.com/@CNBC",
    category: "Business",
    subscribers: "4M+",
    description: "Berita bisnis, ekonomi, dan pasar global terkini.",
    language: "English",
  },
  {
    name: "Bloomberg Originals",
    url: "https://www.youtube.com/@business",
    category: "Business",
    subscribers: "4M+",
    description: "Liputan ekonomi, bisnis global, dan inovasi industri.",
    language: "English",
  },
  {
    name: "Forbes",
    url: "https://www.youtube.com/@Forbes",
    category: "Business",
    subscribers: "3M+",
    description: "Wawancara pemimpin bisnis dan insight dunia entrepreneur.",
    language: "English",
  },
  {
    name: "Entrepreneur",
    url: "https://www.youtube.com/@entrepreneur",
    category: "Business",
    subscribers: "4M+",
    description: "Strategi pertumbuhan bisnis, marketing, dan startup.",
    language: "English",
  },

  {
    name: "Google DeepMind",
    url: "https://www.youtube.com/@GoogleDeepMind",
    category: "AI",
    subscribers: "1M+",
    description: "Riset AI terkini langsung dari tim pengembangan model.",
    language: "English",
  },
  {
    name: "NVIDIA AI",
    url: "https://www.youtube.com/@NVIDIAAIDeveloper",
    category: "AI",
    subscribers: "1M+",
    description: "Konten AI engineering, model, dan komputasi akselerasi.",
    language: "English",
  },

  {
    name: "Computerphile",
    url: "https://www.youtube.com/@Computerphile",
    category: "Security",
    subscribers: "2.7M+",
    description: "Pembahasan keamanan komputer dan konsep CS mendalam.",
    language: "English",
  },
  {
    name: "Seytonic",
    url: "https://www.youtube.com/@Seytonic",
    category: "Security",
    subscribers: "1M+",
    description: "Konten cyber security dan threat awareness untuk publik.",
    language: "English",
  },

  {
    name: "Linda Raynier",
    url: "https://www.youtube.com/@LindaRaynier",
    category: "Career",
    subscribers: "1.6M+",
    description: "Panduan interview, CV, dan strategi pengembangan karier.",
    language: "English",
  },
  {
    name: "Don Georgevich",
    url: "https://www.youtube.com/@DonGeorgevich",
    category: "Career",
    subscribers: "1.4M+",
    description: "Tips menjawab interview dan persiapan kerja profesional.",
    language: "English",
  },

  {
    name: "Techquickie",
    url: "https://www.youtube.com/@techquickie",
    category: "Utilities",
    subscribers: "4M+",
    description: "Penjelasan cepat istilah dan teknologi sehari-hari.",
    language: "English",
  },
  {
    name: "Austin Evans",
    url: "https://www.youtube.com/@austinevans",
    category: "Utilities",
    subscribers: "5M+",
    description: "Review gadget, setup desk, dan tren produk teknologi.",
    language: "English",
  },
  {
    name: "iJustine",
    url: "https://www.youtube.com/@iJustine",
    category: "Utilities",
    subscribers: "7M+",
    description: "Konten teknologi, aplikasi, dan pengalaman produk baru.",
    language: "English",
  },
  {
    name: "JerryRigEverything",
    url: "https://www.youtube.com/@JerryRigEverything",
    category: "Utilities",
    subscribers: "8M+",
    description: "Durability test perangkat dan edukasi perbaikan gadget.",
    language: "English",
  },

  {
    name: "Blogilates",
    url: "https://www.youtube.com/@blogilates",
    category: "Health",
    subscribers: "9M+",
    description: "Workout plan dan rutinitas kebugaran untuk latihan harian.",
    language: "English",
  },
  {
    name: "FitnessBlender",
    url: "https://www.youtube.com/@fitnessblender",
    category: "Health",
    subscribers: "6M+",
    description: "Program latihan full-body untuk berbagai level kebugaran.",
    language: "English",
  },
  {
    name: "emi wong",
    url: "https://www.youtube.com/@emiwong",
    category: "Health",
    subscribers: "4M+",
    description: "Panduan workout dan gaya hidup sehat untuk pemula.",
    language: "English",
  },
];
